// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CAAPstProductFileSelection.h
// Provide implementation to interface
//    CATIProductFileSelection
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   EXTENSION: CATIPrdCommonFileSelection
//   TIE: CATIProductFileSelection
//End CAA2 Wizard Generation Report
//
//  Aug 2003  Creation: Code generated by the CAA wizard  sxy
//===================================================================
#ifndef CAAPstProductFileSelection_H
#define CAAPstProductFileSelection_H

#include "CATPrdCommonFileSelection.h"


class CATIContainer;
class CATIProduct;
//-----------------------------------------------------------------------

/**
 * Class Class extending the object "CATIPrdCommonFileSelection".
 * <br>
 * It implements the interfaces :
 *  <ol>
 *  <li>@see ProductStructure.CATIProductFileSelection
 *  </ol>
 */
class CAAPstProductFileSelection: public CATPrdCommonFileSelection
{
	CATDeclareClass;

public:

	// Standard constructor and destructor for an implementation class
	// -----------------------------------------------------------------
	CAAPstProductFileSelection ();
	virtual ~CAAPstProductFileSelection ();

	/**
	 * @see ProductStructure.CATIProductFileSelection#ExtractProducts()
	 */
	HRESULT ExtractProducts (CATIContainer*, CATIProduct*,
				 CATListValCATBaseUnknown_var*&);


private:
	// The copy constructor and the = operator must not be implemented
	// -------------------------------------------------------------------
	CAAPstProductFileSelection (CAAPstProductFileSelection &);
	CAAPstProductFileSelection& operator=(CAAPstProductFileSelection&);

};

//-----------------------------------------------------------------------

#endif
