# COPYRIGHT DASSAULT SYSTEMES 1994-2000
#======================================================================
# Imakefile for module CAAOmmImpl.m
#======================================================================
#
#  Jan 2000  Creation: Code generated by the CAA wizard  LLE
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
LINK_WITH=JS0GROUP                    \
		  CATMathematics           \
		  CATGeometricObjects      \
		  CATNewTopologicalObjects \
		  CATBasicTopologicalOpe   \
		  CATTopologicalOperators  \
          CATObjectModelerBase     \
          CATObjectSpecsModeler    \
          CATMecModInterfaces      \
		  CATMechanicalModeler     \
          CAAOmmInterfaces
