# COPYRIGHT DASSAULT SYSTEMES 2007
#======================================================================
# Imakefile for module CAAMmrImportWithClientId.m
#======================================================================
#
#  May 2007  Creation: Code generated by the CAA wizard  kow
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) MecModItfCPP \
			 AC0SPBAS JS0CORBA NS0S3STR \
			 AD0XXBAS CATOmbLifeCycle AS0STARTUP\
			 JS0STR CAAMmrUtilities \
   	         CATObjectModelerBase CATObjectSpecsModeler \
             CATMecModInterfaces CATMechanicalModeler \
             

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
