# COPYRIGHT DASSAULT SYSTEMES 1999
#
# LOAD MODULE
#
BUILT_OBJECT_TYPE=LOAD MODULE

LINK_WITH = CATPrint  CATPrt JS0FM JS0GROUP CATVisualization CATViz DI0PANV2 CAAPrtPrintableObjects

OS = Windows_NT
MKMFC_DEPENDENCY = yes
LOCAL_LDFLAGS = $(SUB_WIN)

OS = SunOS
SYS_LIBS = -lXm -lXt -lX11

OS = AIX
SYS_LIBS = -lXm -lXt -lX11

OS = HP-UX
SYS_LIBS = -lXm -lXt -lX11

OS = IRIX
SYS_LIBS = -lXm -lXt -lX11
LOCAL_CCFLAGS  = -float
LOCAL_CFLAGS   = -float

