# COPYRIGHT Dassault Systemes 2009
#======================================================================
# Imakefile for module CAACloECVPercentFill.m
#======================================================================
#
#  May 2009  Creation: Code generated by the CAA wizard  KOZ
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0FM JS0GROUP CATCommonLayoutItfUUID CATCommonLayoutItfCPP CATMathematics
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
