// COPYRIGHT Dassault Systemes 2005
//===================================================================
//
// CAAUEUnixNtMapping.h
// Provide implementation to interface
//    CATIPDMUnixNTMapping

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	CATIPDMUnixNTMapping
//EXTENSIONTYPE:	DataExtension

//    TIE: CATIPDMUnixNTMapping

//End CAA2 Wizard Generation Report
//
//  Mar 2005  Creation: Code generated by the CAA wizard  dpd
//===================================================================
#ifndef CAAUEUnixNtMapping_H
#define CAAUEUnixNtMapping_H

#include "CATBaseUnknown.h"
#include "CATUnicodeString.h"

//-----------------------------------------------------------------------

/**
*/
class CAAUEUnixNtMapping: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     CAAUEUnixNtMapping ();
     virtual ~CAAUEUnixNtMapping ();

    /**
     * Implements a function from an interface.
     * @href CATIPDMUnixNTMapping#UnixPathToNTPath
     */
     HRESULT UnixPathToNTPath (CATUnicodeString  iUnixPath  , CATUnicodeString&  oNTPath ) ;

    /**
     * Implements a function from an interface.
     * @href CATIPDMUnixNTMapping#NtPathToUnix
     */
     HRESULT NtPathToUnix (CATUnicodeString  iNTPath   , CATUnicodeString&  oUnixPath ) ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  CAAUEUnixNtMapping (CAAUEUnixNtMapping &);
  CAAUEUnixNtMapping& operator=(CAAUEUnixNtMapping&);

};

//-----------------------------------------------------------------------

#endif
