# COPYRIGHT DASSAULT SYSTEMES 2005
#======================================================================
# Imakefile for module CAAEhfFlatteningParametersCreate.m
#======================================================================
#
#  September 2005  Creation: Code generated by the CAA wizard  VEI
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) \
            JS0CORBA AS0STARTUP AC0SPBAS AD0XXBAS \
            CATObjectModelerBase CATMathematics CATMathStream \
            CATEhfInterfaces CATElectricalInterfaces CATProductStructure1 \
            


# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
