# COPYRIGHT DASSAULT SYSTEMES 2003
#======================================================================
# Imakefile for module CAAPstProductFileSelection.m
#======================================================================
#
#  Aug 2003  Creation: Code generated by the CAA wizard  sxy
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
LINK_WITH = JS0FM JS0GROUP AS0STARTUP AC0XXLNK

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
