/**
 * @quickreview bsr 04:07:16 // Remove the XML file definition in method Dispose
 */
// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CAAEAniCfgInit.cpp
// Header definition of CAAEAniCfgInit
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jan 2003  Creation: Code generated by the CAA wizard  
//===================================================================
#include "CAAEAniCfgInit.h"

#include "CATFrmEditor.h"
#include "CATDocument.h"
#include "CATISamAccess.h"
#include "CATIContainer.h"
#include "CATISamImageDisplayManager.h"
#include "CATISamImageFactory.h"
#include "CATISamAnalysisContext.h"
#include "CATOsmSUHandler.h"

#include "CATISamProviders.h"                     // Analysis Contextual menu
#include "CATISamCtxMenuProvider.h"
#include "CAAAniCtxMenu.h"

#include "CATIWorkbenchInitialization.h"          // Implemented interface

CATImplementClass(CAAEAniCfgInit, CodeExtension, CATBaseUnknown,CAAAniCfg_init );

 
//-----------------------------------------------------------------------------
// CAAEAniCfgInit : constructor
//-----------------------------------------------------------------------------
CAAEAniCfgInit::CAAEAniCfgInit():
    CATBaseUnknown()
{}

//-----------------------------------------------------------------------------
// CAAEAniCfgInit : destructor
//-----------------------------------------------------------------------------
CAAEAniCfgInit::~CAAEAniCfgInit()
{}
// Tie the implementation to its interface
// ---------------------------------------
#include "TIE_CATIWorkbenchInitialization.h"
TIE_CATIWorkbenchInitialization( CAAEAniCfgInit );

//-----------------------------------------------------------------------------
// Implements CATIWorkbenchInitialization::Init
//-----------------------------------------------------------------------------
void CAAEAniCfgInit::Init ()
{
  CATFrmEditor * pEditor = CATFrmEditor::GetCurrentEditor();
  if (NULL == pEditor) return;

//=====================================
// Retrieves the Analysis document from the Editor.
  CATDocument * pDoc = pEditor -> GetDocument();
  CATISamAccess * piDocAccess =  NULL;
  CATIContainer * piSpecContainer = NULL;
  CATISamImageDisplayManager_var spSpmDisplay ;

  if (pDoc)
    pDoc -> QueryInterface(IID_CATISamAccess, (void**) &piDocAccess);

  if ( piDocAccess)
  {
	  piDocAccess -> GetSpecContainer(piSpecContainer); // Container for feature
    
    CATIContainer * piContainer = NULL;
    piDocAccess -> GetPostproContainer(piContainer); // Container for postprocessing
    if (piContainer)
    {
      spSpmDisplay = piContainer;
  	  piContainer -> Release(); piContainer = NULL;
    }
  	piDocAccess -> Release(); piDocAccess = NULL;
	if ( piSpecContainer ) 
		piSpecContainer -> Release(); piSpecContainer = NULL;
  }

//=====================================
// Open CAAAniCatalog.feat catalog
    CATUnicodeString CataName ("CAAAniCatalog.CATfct");
    CATUnicodeString CataId   ("CAAAniCatalog");
	CATUnicodeString  novelSUType("AeroDynamicSet");
    CATOsmSUHandler   novelSUHandler(novelSUType, CataId, CataName);

//=====================================
// Postprocessing configuration : - activation
//                                - dynamic query 
//                                - Amplified deformed mode.
  if (!! spSpmDisplay)  
  {
    /*spSpmDisplay -> SetDisplayMode    (1);
    spSpmDisplay -> SetPreHilightMode (1);
    spSpmDisplay -> SetDeformationMode(1);
*/
//                                - Define the XML file definition.
    CATISamImageFactory * piImageFactory = NULL;
    spSpmDisplay -> QueryInterface(IID_CATISamImageFactory,(void **)& piImageFactory);
    if (piImageFactory)
    {
      piImageFactory -> AddImageFile ("CAAAniImages.xml");
      piImageFactory -> Release();
    }
  }
  CATISamAnalysisContext * piContextEditor = NULL;
  pEditor -> QueryInterface (IID_CATISamAnalysisContext, (void**) & piContextEditor);
  if (piContextEditor)
  {
	  piContextEditor -> SetVisuModes(CATSamVisuModeMeshing,
      CATSamVisuModeMeshing|CATSamVisuModePreProcessing|CATSamVisuModePostProcessing);
	  piContextEditor -> Release(); piContextEditor = NULL;
  }

//=====================================
// Declare a contextual menu provider
  CATISamProviders* piProvider = NULL;
  if (pDoc)
    pDoc -> QueryInterface(IID_CATISamProviders, (void **) &piProvider);

  if (piProvider)
  {
    CAAAniCtxMenu * piCtxMenu = new CAAAniCtxMenu ();
    if (piCtxMenu) {
      piProvider -> AddProvider(IID_CATISamCtxMenuProvider,piCtxMenu);
      piCtxMenu -> Release(); piCtxMenu = NULL;
    }
    piProvider -> Release(); piProvider = NULL;
  }

}
//-----------------------------------------------------------------------------
// Implements CATIWorkbenchInitialization::Dispose
//-----------------------------------------------------------------------------
void CAAEAniCfgInit::Dispose ()
{
  CATFrmEditor * pEditor = CATFrmEditor::GetCurrentEditor();
  if (NULL == pEditor) return;
  CATISamProviders * piProvider = NULL;
  CATDocument * pDoc = pEditor -> GetDocument();
  if (pDoc)
    pDoc -> QueryInterface(IID_CATISamProviders, (void **) &piProvider);

  // - Remove the XML file definition added in init method
  CATISamAccess * piDocAccess =  NULL;
  CATISamImageDisplayManager_var spSpmDisplay ;

  if (pDoc)
    pDoc -> QueryInterface(IID_CATISamAccess, (void**) &piDocAccess);

  if ( piDocAccess)
  {
    CATIContainer * piContainer = NULL;
    piDocAccess -> GetPostproContainer(piContainer); // Container for postprocessing
    if (piContainer)
    {
      spSpmDisplay = piContainer;
  	  piContainer -> Release(); piContainer = NULL;
    }
  	piDocAccess -> Release(); piDocAccess = NULL;
  }

  if (!! spSpmDisplay)  
  {
    // - Remove the XML file definition.
    CATISamImageFactory * piImageFactory = NULL;
    spSpmDisplay -> QueryInterface(IID_CATISamImageFactory,(void **)& piImageFactory);
    if (piImageFactory)
    {
      piImageFactory -> RemoveImageFile ("CAAAniImages.xml");
      piImageFactory -> Release();
    }
  }


  if (piProvider)
  {
    CATLISTP(CATBaseUnknown) * listProvider = new CATLISTP(CATBaseUnknown);
    CATAssert(listProvider);
    piProvider -> ListProviders(CATISamCtxMenuProvider::ClassId(),&listProvider);
	  if(listProvider )
	  {
      for(int i=1;i<=listProvider->Size();i++)
      {
        CATBaseUnknown * pProvider = (*listProvider)[i];
        if (!pProvider) continue;
        if (pProvider->IsAKindOf("CAAAniCtxMenu"))
          piProvider -> RemoveProvider(IID_CATISamCtxMenuProvider,pProvider);
      }
       delete listProvider;listProvider=NULL;
    }

    piProvider -> Release(); piProvider = NULL;
  }
}
