# COPYRIGHT DASSAULT SYSTEMES 2003
#======================================================================
# Imakefile for module CAAV4iMigrationReportExtraction.m
#======================================================================
#
#  Apr 2003  Creation: Code generated by the CAA wizard  lbv
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = 
# END WIZARD EDITION ZONE

LINK_WITH = SystemUUID JS0GROUP JS0CORBA CATObjectModelerBase CATObjectSpecsModeler CATMecModInterfaces

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
