/**
* @quickReview CRE 03:10:17
*/
//=============================================================================
//
// COPYRIGHT DASSAULT SYSTEMES  2001
//
// Sample code for : Geometric Modeler
// Mission         : Use of the FreeFormOperators framework
//
// Type            : Batch program
// Inputs          : None
// Outputs         : Return Codes (if not null, the model is not saved)
//                    0- OK
//                    1- Null pointer
//
// Coding steps    :  1- Creation of the geometry factory
//                    2- Creation of a PSpline on a sphere
//                    3- Creation of a PNurbs from a CATCrvFittingToNurbsCrv operator
//                    4- Deletion of the  operator
//                    5- Writing the model and closing the geometric container
//                   
//
// How to run it   : CAACrvFittingToNurbsCrv           // to run without storing the NCGM file
//                   CAACrvFittingToNurbsCrv file.NCGM // to run and store the result in file.NCGM                       
//=============================================================================

#include <iostream.h>
#include <iomanip.h>
#include "fstream.h"

// GeometricObjects
#include "CATGeoFactory.h"               // Geometry factory
#include "CATCGMContainerMngt.h"         // Management of the geometry factory
#include "CATCrvLimits.h"                // Limits of a curve
#include "CATSphere.h"                   // Sphere creation
#include "CATPNurbs.h"                   // PNurbs creation
#include "CATCurve.h"                    // Curve  creation

// Mathematics
#include "CATMathAxis.h"                 // Math axis creation

// AdvancedMathematics
#include "CATMathSetOfPointsND.h"        // Set of points in a n dimension space

// FreeFormOperators
#include "CATCrvFittingToNurbsCrv.h"     // To convert surfaces into Nurbs

//------------------------------------------------------------------------------
int main(int    iArgc,   // Number of arguments (0) or (1) 
         char** iArgv)   // Path to the *.NCGM document generated by this program
{
	int rc=0;
	if(2<iArgc) return (1);
	
	char *pFileName = 0;
	int  toStore = 0;
	if (2==iArgc) 
	{
		toStore = 1; 
		pFileName = iArgv[1];
	}
	
	//----------------------------------------------------------------------------
	// 1-Initialize the factory 
	//----------------------------------------------------------------------------
	
    CATGeoFactory* piGeomFactory = ::CATCreateCGMContainer() ;
	if (NULL==piGeomFactory) return (1);
	
	
    //----------------------------------------------------------------------------
	// 2 - Create the geometry 
	//----------------------------------------------------------------------------
	
	// (a) ---- Create the sphere
	// 
	CATMathPoint Center(0.,0.,0.);
	CATMathAxis Axis(Center);
	double Radius = 10.;
	CATSphere * piSupport = piGeomFactory->CreateSphere(Axis,Radius);
	if (NULL==piSupport) 
	{
		::CATCloseCGMContainer(piGeomFactory);
		return (1);
	}
	
	// (b) ---- Create the PSpline on the sphere
	//
	CATLONG32 nbpt=6;
	
	double Pt2D[2];
	CATMathSetOfPointsND Set2D(2, nbpt);
	
	Pt2D[0]=0.; Pt2D[1]=0.;
	Set2D.AddPoint(Pt2D);
	
	Pt2D[0]=1.; Pt2D[1]=2.;
	Set2D.AddPoint(Pt2D);
	
	Pt2D[0]=6.; Pt2D[1]=1.;
	Set2D.AddPoint(Pt2D);
	
	Pt2D[0]=3.; Pt2D[1]=-6.;
	Set2D.AddPoint(Pt2D);
	
	Pt2D[0]=1.; Pt2D[1]=-8.;
	Set2D.AddPoint(Pt2D);
	 	 
	Pt2D[0]=0.; Pt2D[1]=-15.;
	Set2D.AddPoint(Pt2D);
	
	CATPSpline * piPSpline = piGeomFactory->CreatePSpline(&Set2D,0,1,NULL,piSupport);
	if (NULL==piPSpline) 
	{
		::CATCloseCGMContainer(piGeomFactory);
		return (1);
	}
	
	// (c) ---- Get the curve from the PSpline
	//
	CATCurve * piCurve = (CATCurve*)piPSpline;
    
	//----------------------------------------------------------------------------
	// 3 - Create and 3manipulate a PNurbs from a 
	//     CATCrvFittingToNurbsCrv operator
	//----------------------------------------------------------------------------
	
    //  (a) --- Define the maximum deviation between the input and the output curve
	//
    double maxdeviation = 0.001;
	
	//  (b) --- Retrieve the CATCurve limits to be specified as the argument 3 of the
	//          CATCreateCrvFittingToNurbsCrv global function
    CATCrvLimits crvLimits;
    piCurve->GetLimits(crvLimits);
	
	//  (c) --- Create the operator - The curve to be created is to be rational
	//          Skill mode is set to ADVANCED 
    CATCrvFittingToNurbsCrv * pCrvFitting1 = ::CATCreateCrvFittingToNurbsCrv(piGeomFactory,
		piCurve,
		crvLimits,
		maxdeviation,
		1,
		ADVANCED) ;
		
    //  (d) --- Specifies the minimal length of an arc on the output curve
	//          Should be properly specified with respect to the input curve
	//          length - otherwise the execution results in an abend
	//
	pCrvFitting1->SetInternalMinLength(14);
	
	//  (e) --- Run the operator
	//
	pCrvFitting1->Run();
	
	//  (g) --- Get the resulting PNurbs
	//
	CATPNurbs * piPNurbs1 = pCrvFitting1->GetPNurbs();
	if (NULL==piPNurbs1)
	{
		cout << "piPNurbs1 could not be created" << endl;
	}

	// (f) ---- Display the maximum deviation of the computed curve
	//          Is only meaningful after the Run method has been applied
	//
    cout << "Maximum deviation is " << pCrvFitting1->GetMaxDeviation() << endl;

	//----------------------------------------------------------------------------
	// 4 - Cleaning operations 
	//----------------------------------------------------------------------------
	delete pCrvFitting1;
	pCrvFitting1=NULL;
	piGeomFactory->Remove(piSupport,CATICGMContainer::RemoveDependancies);
	
	//----------------------------------------------------------------------------
	// 5 - Write the model and close the container
	//----------------------------------------------------------------------------
	if(1==toStore)
	{
		cout << "Writing the model" << endl;
#ifdef _WINDOWS_SOURCE
		ofstream filetowrite(pFileName, ios::binary ) ;
#else
		ofstream filetowrite(pFileName,ios::out,filebuf::openprot) ;
#endif
		
		::CATSaveCGMContainer(piGeomFactory,filetowrite);
		filetowrite.close();
	}	
   	
	::CATCloseCGMContainer(piGeomFactory);
	return (rc);
}


//automate:11/09/01:suppression include de CATMathPlane.h
