/**
* @quickReview CRE 03:10:17
*/
//=============================================================================
//
// COPYRIGHT DASSAULT SYSTEMES  2001
//
// Sample code for : Geometric Modeler
// Mission         : Use of the FreeFormOperators framework
//
// Type            : Batch program
// Inputs          : None
// Outputs         : Return Codes (if not null, the model is not saved)
//                   0- OK
//                   1- Null pointer
//
// Coding steps    : 1- Creation of the geometry factory
//                   2- Creation of the revolution surface
//                   3- Creation of a first Nurbs surface
//                      from the CATSurFittingToNurbsSur operator
//                   4- Deletion of the operator
//                   5- Creation of a second Nurbs surface from a new operator
//                   6- Deletion of the second operator
//                   7- Writing of the model and closing of the geometric container
//                   
//
// How to run it   : CAASurFittingToNurbsSur           // to run without storing the NCGM file
//                   CAASurFittingToNurbsSur file.NCGM // to run and store the result in file.NCGM                       
//=============================================================================

#include <iostream.h>
#include <iomanip.h>
#include "fstream.h"

// GeometricObjects
#include "CATGeoFactory.h"               // Geometry factory
#include "CATCGMContainerMngt.h"         // Management of the geometry factory
#include "CATSurLimits.h"                // Limits of a curve
#include "CATNurbsSurface.h"             // NurbsSurface creation
#include "CATSplineCurve.h"              // Spline creation

// Mathematics
#include "CATMathAxis.h"                 // Math axis
#include "CATMath.h"

// AdvancedMathematics

// FreeFormOperators
#include "CATSurFittingToNurbsSur.h"     // To convert surfaces into Nurbs


//------------------------------------------------------------------------------
int main(int    iArgc,   // Number of arguments (0) or (1) 
         char** iArgv)   // Path to the *.NCGM document generated by the program
{
	int rc=0;
	if(2<iArgc) return (1);
	
	char *pFileName = 0;
	int  toStore = 0;
	if (2==iArgc) 
	{
		toStore = 1; 
		pFileName = iArgv[1];
	}
	
	//----------------------------------------------------------------------------
	// 1-Initialize the factory 
	//----------------------------------------------------------------------------
	
    CATGeoFactory* piGeomFactory = ::CATCreateCGMContainer() ;
	if (NULL==piGeomFactory) return (1);
	
	
    //----------------------------------------------------------------------------
	// 2 - Create the geometry (Spline curve and revolution surface)
	//----------------------------------------------------------------------------
	
	// a ---- Create the set of points
	// 
	const CATLONG32 N = 4;
	CATMathSetOfPointsND pointSet(3, N);
	
	double Point1[3]={-20.0, 0.0, 5.0} ;
	double Point2[3]={-15.0, 5.0, 10.0} ;
	double Point3[3]={-2.0, 10.0, 15.0} ;
	double Point4[3]={ 5.0, 13.0, 20.0} ;
	
	pointSet.AddPoint(Point1); //Point1
	pointSet.AddPoint(Point2); //Point2
	pointSet.AddPoint(Point3); //Point3
	pointSet.AddPoint(Point4); //Point4
	
	// b ---- Define the parameterization
	//
	double Params[N];
	
	Params[0] = 1;
	Params[1] = 2;
	Params[2] = 3;
	Params[3] = 5;
    
	// c ---- Create the spline
	//
	CATSplineCurve * piSplineCurve = 
		piGeomFactory->CreateSplineCurve(&pointSet,0,1,2,NULL);
	if (NULL==piSplineCurve)
	{
		::CATCloseCGMContainer(piGeomFactory);
		return (1);
	}     
    
	// d ---- Create the revolution surface
	//
	CATMathAxis RevAxis = CATMathAxis();
	
	CATCurve * piCurve = (CATCurve*)piSplineCurve;
	
	CATRevolutionSurface * piRevSurf =
		piGeomFactory->CreateRevolutionSurface (piCurve, RevAxis, 0., CATPI ) ;
	if (NULL==piRevSurf)
	{
		::CATCloseCGMContainer(piGeomFactory);
		return (1);
	}     
	
	//----------------------------------------------------------------------------
	// 3 - Create a first Nurbs surface from the 
	//     CATSurFittingToNurbsSur operator 
	//----------------------------------------------------------------------------
    
	// (a) --- Retrieve the CATSurface pointer intended to be passed as the 
	// argument 2 of the CATCreateSurFittingToNurbsSur global function
	//
    CATSurface * piSurface = (CATSurface*)piRevSurf;
	if (NULL==piSurface)
	{
		::CATCloseCGMContainer(piGeomFactory);
		return (1);
	}  
	
	// (b) --- Retrieve the CATSurLimits intended to be passed as the
	// argument 3 of the CATCreateSurFittingToNurbsSur global function
	//
    CATSurLimits surLimits;
    piSurface->GetLimits(surLimits);
	
    // (c) --- Initialize some variables to be used later on when testing the
	// generated surfaces
	//
	double maxDeviat = 0.;
	CATLONG32 IsExact = 1;
	
    
	// (d) --- Create the first CATSurFittingToNurbsSur operator 
	//
    CATSurFittingToNurbsSur * pSurFitting1 = 
		::CATCreateSurFittingToNurbsSur(piGeomFactory,
		piSurface,
		surLimits,
		0.001,
		1,
		ADVANCED);
	
    if (NULL==pSurFitting1)
	{
		::CATCloseCGMContainer(piGeomFactory);
		return (1);
	}
	
    cout << "-- Nurbs 1 ----------------- " << endl;
	
    // (e) --- Run the operator
	//
    pSurFitting1->Run();
	
	// (f) --- Retrieve the created NurbsSurface
	//
    CATNurbsSurface * pNurbsSurf1 = pSurFitting1->GetNurbsSurface();
	if (NULL==pNurbsSurf1)
	{
		::CATCloseCGMContainer(piGeomFactory);
		return (1);
	}
	
	// (g) --- Determine whether the transformation is exact 
	// "Transformation exact" expected as the surface
	// has been specified rational 
	//
	IsExact = pSurFitting1->IsExactTransformation();
	if (IsExact == 0) cout << "Transformation not exact" << endl;
	else {cout << "Exact transformation" << endl;}
	
	// (h) --- Display the maximum deviation on the standard output - 0 expected
	//
	maxDeviat = pSurFitting1->GetMaxDeviation();
	cout << "Maximum deviation of surface 1 " <<  maxDeviat << endl;
	
    //----------------------------------------------------------------------------
	// 4 - Delete the first operator
	//----------------------------------------------------------------------------
    
	delete pSurFitting1;
	pSurFitting1=NULL;
	
	//----------------------------------------------------------------------------
	// 5 - Create a second Nurbs surface from the 
	//     CATSurFittingToNurbsSur operator 
	//----------------------------------------------------------------------------
	
	// (a) --- Create the second CATSurFittingToNurbsSur operator
	//
	CATSurFittingToNurbsSur * piSurFitting2 = 
		::CATCreateSurFittingToNurbsSur(piGeomFactory,
		piSurface,
		surLimits,
		0.001,
		1,
		ADVANCED);
	
    if (NULL==piSurFitting2)
	{
		::CATCloseCGMContainer(piGeomFactory);
		return (1);
	}
	
    cout << "-- Nurbs 2 - Minimum length = 32 -- " << endl;
	
	// (b) --- Set the minimum length of an arc to 32
	//
    piSurFitting2->SetInternalMinLength(32);
	
	// (c) --- Run the operator
	//
    piSurFitting2->Run();
	
	// (d) --- Retrieve the created NurbsSurface
	//
    CATNurbsSurface * pNurbsSurf2= piSurFitting2->GetNurbsSurface();
	if (NULL==pNurbsSurf2)
	{
		::CATCloseCGMContainer(piGeomFactory);
		return (1);
	}
	
   	// (e) --- Determine whether the transformation is exact 
	//
	IsExact = piSurFitting2->IsExactTransformation();
	if (IsExact == 0) cout << "Transformation not exact" << endl;
	else {cout << "Exact transformation" << endl;}
	
	// (f) --- Display the maximum deviation
	//
	maxDeviat = piSurFitting2->GetMaxDeviation();
	cout << "Maximum deviation of surface 2 " <<  maxDeviat << endl;
	
	//----------------------------------------------------------------------------
	// 6 - Delete the second operator
	//----------------------------------------------------------------------------
    delete piSurFitting2;
	piSurFitting2=NULL;
	
	//----------------------------------------------------------------------------
	// 7 - Write the model and close the container
	//----------------------------------------------------------------------------
	if(1==toStore)
	{
		cout << "Writing the model" << endl;
#ifdef _WINDOWS_SOURCE
		ofstream filetowrite(pFileName, ios::binary ) ;
#else
		ofstream filetowrite(pFileName,ios::out,filebuf::openprot) ;
#endif
		
		::CATSaveCGMContainer(piGeomFactory,filetowrite);
		filetowrite.close();
	}	
   	
	::CATCloseCGMContainer(piGeomFactory);
	return (rc);
}


//automate:11/09/01:suppression include de CATMathSetOfPoints.h
//automate:11/09/01:suppression include de CATMathPlane.h
