# COPYRIGHT DASSAULT SYSTEMES 2007
#======================================================================
# Imakefile for module CAAEhfGreenLineMechPartAndSupportInBNS.m
#======================================================================
#
#  January 2006  Creation: Code generated by the CAA wizard  VEI
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) \
            JS0CORBA AS0STARTUP AC0SPBAS AD0XXBAS \
            CATObjectModelerBase CATMathematics CATMathStream \
            CATEhfInterfaces CATElectricalInterfaces CATProductStructure1
            
# GLY : 25:01:2007, CATEhiInterfaces
# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
