// COPYRIGHT Dassault Systemes 2005
//===================================================================
//
// CAAUEUnixNtMapping.cpp
// Provide implementation to interface
//    CATIPDMUnixNTMapping
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Mar 2005  Creation: Code generated by the CAA wizard  dpd
//===================================================================
#include "CAAUEUnixNtMapping.h"

#include "CATGetEnvValue.h"
#include <iostream.h>

 
CATImplementClass(CAAUEUnixNtMapping,
                  DataExtension,
                  CATBaseUnknown,
                  CATPdmUnixNtMapping  );
 

//-----------------------------------------------------------------------------
// CAAUEUnixNtMapping : constructor
//-----------------------------------------------------------------------------
CAAUEUnixNtMapping::CAAUEUnixNtMapping():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// CAAUEUnixNtMapping : destructor
//-----------------------------------------------------------------------------
CAAUEUnixNtMapping::~CAAUEUnixNtMapping()
{
}
 
// Link the implementation to its interface
// ---------------------------------------



//TIE or TIEchain definitions
#include "TIE_CATIPDMUnixNTMapping.h"
TIE_CATIPDMUnixNTMapping( CAAUEUnixNtMapping);


//Methods implementation

//-----------------------------------------------------------------------------
// Implements CATIPDMUnixNTMapping::UnixPathToNTPath
//-----------------------------------------------------------------------------
HRESULT CAAUEUnixNtMapping::UnixPathToNTPath (CATUnicodeString  iUnixPath , CATUnicodeString&  oNTPath)
{
	cout << "UnixPathToNTPath: IN iUnixPath=|" << iUnixPath.ConvertToChar() << "|" << endl << flush;
	char* unixToNtPath = NULL;
	CATLibStatus LibStatus = CATGetEnvValue("CAA_UNIX_TO_NT_PATH", &unixToNtPath);
	if(unixToNtPath != "")
	{
	  CATUnicodeString UNIXtoNTpath(unixToNtPath);
	  free(unixToNtPath);
	  oNTPath = CATUnicodeString(iUnixPath);

	  int cut = oNTPath.SearchSubString("/", 0, CATUnicodeString::CATSearchModeBackward);
	  oNTPath.Remove(0, cut);
	  oNTPath.ReplaceAll("/", "\\"); 
	  oNTPath = UNIXtoNTpath.SubString(0,2) + oNTPath;

  cout << "UnixPathToNTPath: OUT oNTPath=|" << oNTPath.ConvertToChar() << "|" << endl << flush;
	cout << endl << flush;
	}
	else 
	{
	  cout<<"CAA_UNIX_TO_NT_PATH must be valuated"<<endl<< flush;
	  return E_FAIL;
	}

   return S_OK;
}

//-----------------------------------------------------------------------------
// Implements CATIPDMUnixNTMapping::NtPathToUnix
//-----------------------------------------------------------------------------
HRESULT CAAUEUnixNtMapping::NtPathToUnix (CATUnicodeString  iNTPath  , CATUnicodeString&  oUnixPath)
{

#ifdef _WINDOWS_SOURCE
  char* ntToUnixPath = NULL;
  CATLibStatus LibStatus = CATGetEnvValue("CAA_NT_TO_UNIX_PATH", &ntToUnixPath);
  CATUnicodeString NTtoUNIXpath(ntToUnixPath);
  if(NTtoUNIXpath != "")
  {
	oUnixPath = CATUnicodeString(iNTPath);
	int cut = oUnixPath.SearchSubString("\\", 0, CATUnicodeString::CATSearchModeBackward);
	oUnixPath.Remove(0, cut);
	oUnixPath.ReplaceAll("\\", "/"); // only needed for old code
	oUnixPath = NTtoUNIXpath + oUnixPath;
	free(ntToUnixPath);
  }
  else 
  {
    cout<<"CAA_NT_TO_UNIX_PATH must be valuated"<<endl<< flush;
    return E_FAIL;
  }
#else // UNIX
  oUnixPath=iNTPath;
  cout << "oUnixPath=iNTPath" <<endl<< flush;
#endif
  
  cout << "NtPathToUnix: OUT oUnixPath=|" << oUnixPath.ConvertToChar() << "|" << endl << flush;
  cout << endl << flush;
  return S_OK;
}

