// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CAAEAniCfgInit.h
// Header definition of CAAEAniCfgInit
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jan 2003  Creation: Code generated by the CAA wizard  
//===================================================================
#ifndef CAAEAniCfgInit_H
#define CAAEAniCfgInit_H

#include "CATBaseUnknown.h"
class CATDocument;
//-----------------------------------------------------------------------

/**
 * Class Class extending the object "CAAAniCfg".
 * <br>
 * It implements the interfaces :
 *  <ol>
 *  <li>@see ApplicationFrame.CATIWorkbenchInitialization
 *  </ol>
 */
class  CAAEAniCfgInit: public CATBaseUnknown
{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     CAAEAniCfgInit ();
     virtual ~CAAEAniCfgInit ();

    /**
     * Implements a function from an interface.
     * @see ApplicationFrame.CATIWorkbenchInitialization#Init
     */
     void Init () ;

    /**
     * Implements a function from an interface.
     * @see ApplicationFrame.CATIWorkbenchInitialization#Dispose
     */
     void Dispose () ;


  private:

  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  CAAEAniCfgInit (CAAEAniCfgInit &);
  CAAEAniCfgInit& operator=(CAAEAniCfgInit&);


};

//-----------------------------------------------------------------------

#endif
