// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CAAPuiPRDWorkshopAddin.cpp
// Provide implementation to interface
//    CATIPRDWorkshopAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Aug 2003  Creation: Code generated by the CAA wizard  avm
//===================================================================
#include "CAAPuiPRDWorkshopAddin.h"
#include "CAAPuiPRDWorkshopAddinTrace.h"

// ApplicationFrame framework
#include "CATCreateWorkshop.h"
#include "CATCommandHeader.h"
MacDeclareHeader(CAAPuiPRDWorkshopAddinHeader);
 
// ProductStructureUI framework
#include "CATIPRDWorkshopAddin.h"

CATImplementClass(CAAPuiPRDWorkshopAddin,
                  Implementation,
                  CATBaseUnknown,
                  CATnull);
 
// Tie the implementation to its interface
// ---------------------------------------
#include "TIE_CATIPRDWorkshopAddin.h"
TIE_CATIPRDWorkshopAddin(CAAPuiPRDWorkshopAddin);

//-----------------------------------------------------------------------------
// CAAPuiPRDWorkshopAddin : constructor
//-----------------------------------------------------------------------------
CAAPuiPRDWorkshopAddin::CAAPuiPRDWorkshopAddin():
	CATBaseUnknown()
{
	CAAPuiPRDWorkshopAddinTRACE("CAAPuiPRDWorkshopAddin - Constructor");
}

//-----------------------------------------------------------------------------
// CAAPuiPRDWorkshopAddin : destructor
//-----------------------------------------------------------------------------
CAAPuiPRDWorkshopAddin::~CAAPuiPRDWorkshopAddin()
{
	CAAPuiPRDWorkshopAddinTRACE("CAAPuiPRDWorkshopAddin - Destructor");
}

//-----------------------------------------------------------------------------
// Implements CATIWorkbenchAddin::CreateCommands
//-----------------------------------------------------------------------------
void CAAPuiPRDWorkshopAddin::CreateCommands ()
{
	CAAPuiPRDWorkshopAddinTRACE(">> CAAPuiPRDWorkshopAddin::CreateCommands()");
   
	// Instantiates the command header for the command
	new CAAPuiPRDWorkshopAddinHeader
		("CAAPuiPRDWorkshopAddinCmd1",		// command name
		 "CAAPuiPRDWorkshopAddin",		// lib name
		 "CAAPuiPRDWorkshopAddinCmd",		// class name
		 (void*) NULL);
   
	CAAPuiPRDWorkshopAddinTRACE("<< CAAPuiPRDWorkshopAddin::CreateCommands()");
}

//-----------------------------------------------------------------------------
// Implements CATIWorkbenchAddin::CreateToolbars
//-----------------------------------------------------------------------------
CATCmdContainer * CAAPuiPRDWorkshopAddin::CreateToolbars ()
{
	CAAPuiPRDWorkshopAddinTRACE(">> CAAPuiPRDWorkshopAddin::CreateToolbars()");

	// Declaration of toolbar for Addin
	NewAccess(CATCmdContainer, pToolbarContainer, 
		  CAAPuiPRDWorkshopAddinToolbar);
	NewAccess(CATCmdStarter, pCommandStarter, 
		  CAAPuiPRDWorkshopAddinStarter);

	// Arranging the command within the toolbar
	SetAccessCommand(pCommandStarter, "CAAPuiPRDWorkshopAddinCmd1");
	SetAccessChild(pToolbarContainer, pCommandStarter);

	int visibleFlag = 1;
	AddToolbarView (pToolbarContainer, visibleFlag, Top);
   
	CAAPuiPRDWorkshopAddinTRACE("<< CAAPuiPRDWorkshopAddin::CreateToolbars()");
	return pToolbarContainer;
}
