// COPYRIGHT DASSAULT SYSTEMES 2000
//===================================================================
//
// CAAEEntityBoxSubscriber.h
// Provide implementation to interface
//    CATISamMeshSubscriber
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Mar 2000  Creation: Code generated by the CAA wizard  
//===================================================================
#ifndef CAAEEntityBoxSubscriber_H
#define CAAEEntityBoxSubscriber_H

#include "CATEAnalysisEntityPreproSubscriber.h"

//-----------------------------------------------------------------------

/**
 * Class Class extending the object "ANIFreeGroupEntityTst".
 * <br>
 * It implements the interfaces :
 *  <ol>
 *  <li>@see CATAnalysisInterfaces.CATISamMeshSubscriber
 *  </ol>
 */
class CAAEEntityBoxSubscriber: public CATEAnalysisEntityPreproSubscriber
{
	CATDeclareClass;

	public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
		CAAEEntityBoxSubscriber ();
		virtual ~CAAEEntityBoxSubscriber ();


	private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
		CAAEEntityBoxSubscriber (CAAEEntityBoxSubscriber &);
		CAAEEntityBoxSubscriber& operator=(CAAEEntityBoxSubscriber&);
};

//-----------------------------------------------------------------------

#endif
