// COPYRIGHT Dassault Systemes 2007
//===================================================================
//
// CAAMmrPartWksFreezeUnfreezeCmd.h
// The state chart based command: CAAMmrPartWksFreezeUnfreezeCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA Wizard Generation Report
//   STATECOMMAND
//End CAA Wizard Generation Report
//
//  May 2007  Creation: Code generated by the CAA wizard  GRO
//===================================================================
#ifndef CAAMmrPartWksFreezeUnfreezeCmd_H
#define CAAMmrPartWksFreezeUnfreezeCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"

class CATPathElementAgent;
//CAA WIZARD FORWARD DECLARATION SECTION: DO NOT EDIT
//END CAA WIZARD FORWARD DECLARATION SECTION

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class CAAMmrPartWksFreezeUnfreezeCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( CAAMmrPartWksFreezeUnfreezeCmd, CATStateCommand )

  public:

  CAAMmrPartWksFreezeUnfreezeCmd();
  virtual ~CAAMmrPartWksFreezeUnfreezeCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

   CATBoolean FreezeOrUnfreeze(void* iData);

  private:
	  CATPathElementAgent* _daObjectToSelect;
};

//----------------------------------------------------------------------

#endif
