#ifndef CAAUipFilteringCriteriaExt_H
#define CAAUipFilteringCriteriaExt_H
// COPYRIGHT Dassault Systemes 2005
//===================================================================
//
// CAAUipFilteringCriteriaExt.cpp
// Provide implementation to interface
//    CATIEleUipFilteringCriteria
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Jun 2002  Creation: Code generated by the CAA wizard  LVT
//===================================================================

#include "CATBaseUnknown.h"
class CATListValCATUnicodeString;

class CAAUipFilteringCriteriaExt : public CATBaseUnknown
	{
	CATDeclareClass;
	public:
		CAAUipFilteringCriteriaExt();
		virtual ~CAAUipFilteringCriteriaExt();

		HRESULT ListCriteria (const CATListValCATUnicodeString * iListOfSystems , CATListValCATUnicodeString *& oListOfCriteria);
		HRESULT ListWires (const CATListValCATUnicodeString * iListOfSystems , const CATListValCATUnicodeString * iListOfCriteria , CATListValCATUnicodeString *& oListOfWires);
		HRESULT ListSystems (CATListValCATUnicodeString *& oListOfSystems);
	private:

		CAAUipFilteringCriteriaExt(const CAAUipFilteringCriteriaExt &);
		CAAUipFilteringCriteriaExt& operator=(const CAAUipFilteringCriteriaExt &); 

	};

#endif
