# COPYRIGHT DASSAULT SYSTEMES 2005
#======================================================================
# Imakefile for module CAAPsnUseCase4.m
#======================================================================
#
#  Sep 2005  Creation: Code generated by the CAA wizard  dpd
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP CATPinServices CATObjectModelerBase CATPDMBase
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
