// COPYRIGHT Dassault Systemes 2005
//===================================================================
//
// CAAOBMInterfacesCommand.h
// The state chart based command: CAAOBMInterfacesCommand
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  May 2005  Creation: Code generated by the CAA wizard  auw
//===================================================================
#ifndef CAAOBMInterfacesCommand_H
#define CAAOBMInterfacesCommand_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "CAAOBMInterfacesDlg.h"
#include "CATDialogAgent.h"

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class CAAOBMInterfacesCommand: public CATStateCommand
{
	// Allows customization/internationalization of command's messages
	// ---------------------------------------------------------------
	CmdDeclareResource(CAAOBMInterfacesCommand, CATStateCommand)

public:
	CAAOBMInterfacesCommand();
	//The behavior is passed as an argument to the command
	CAAOBMInterfacesCommand(CATBaseUnknown *iBehavior);
	virtual ~CAAOBMInterfacesCommand();

	/**
	* Defines the command automata.
	* <br>
	* <i>(states, transitions and agents)</i>
	*/
	virtual void     BuildGraph();

	CATStatusChangeRC Cancel( CATCommand * iFromClient, CATNotification * iEvtDat);
	CATStatusChangeRC Desactivate( CATCommand * iFromClient, CATNotification * iEvtDat);
	CATStatusChangeRC Activate( CATCommand * iFromClient, CATNotification * iEvtDat);

private:
	CATBaseUnknown * _Behavior;
	CAAOBMInterfacesDlg* _CAAOBMInterfacesDlg;
	CATDialogAgent* _OK;
	CATDialogAgent* _Cancel;
};

//----------------------------------------------------------------------

#endif
