// COPYRIGHT Dassault Systemes 2005
//===================================================================
//
// CAAOBMInterfacesDlg.h
// The dialog : CAAOBMInterfacesDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  May 2005  Creation: Code generated by the CAA wizard  auw
//===================================================================
#ifndef CAAOBMInterfacesDlg_H
#define CAAOBMInterfacesDlg_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"

class CATIVariableManagement;
//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class CAAOBMInterfacesDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( CAAOBMInterfacesDlg, CATDlgDialog )

  public:

	  //the behavior command is passed as an argument to the dialog
  CAAOBMInterfacesDlg(CATBaseUnknown *iBehavior);
  virtual ~CAAOBMInterfacesDlg();

  //the build method will build the panel. It has to be called after instantiating a new panel
  void Build ();


private:
	void OnPushButtonValueAttWithPub(CATCommand* cmd, CATNotification* evt, CATCommandClientData data);
	void OnChangeAttType(CATCommand* cmd, CATNotification* evt, CATCommandClientData data);
	void OnPushButtonSetLink(CATCommand* cmd, CATNotification* evt, CATCommandClientData data);
	void OnPushButtonChangeAttValue(CATCommand* cmd, CATNotification* evt, CATCommandClientData data);

//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgFrame*      _Frame003;
 CATDlgLabel*      _Label004;
 CATDlgEditor*      _EditorValueOfParm;
 CATDlgPushButton*      _ApplySetValue;
 CATDlgLabel*      _Label007;
 CATDlgLabel*      _Label008;
 CATDlgLabel*      _Label009;
 CATDlgPushButton*      _PushButtonSetLink;
 CATDlgEditor*      _PublicationName;
 CATDlgPushButton*      _PushButton012;
 CATDlgCombo*      _ComboParmType;
//END CAA2 WIZARD WIDGET DECLARATION SECTION

 CATBaseUnknown* _Behavior;

};

//----------------------------------------------------------------------

#endif
