//===================================================================
// COPYRIGHT DASSAULT SYSTEMES 2003+
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework CAAStructureInterfaces.edu
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Jul 2003  Creation: Code generated by the CAA wizard  (Brian Yin)
//===================================================================

AddPrereqComponent ("System"                       , Public);
AddPrereqComponent ("ProductStructure"             , Public);
AddPrereqComponent ("ObjectModelerBase"            , Public);
AddPrereqComponent ("StructureInterfaces"          , Public);
AddPrereqComponent ("Mathematics"                  , Public);
AddPrereqComponent ("GeometricObjects"             , Public);
AddPrereqComponent ("SketcherInterfaces"           , Public);
AddPrereqComponent ("ObjectSpecsModeler"           , Public);
AddPrereqComponent ("KnowledgeInterfaces"          , Public);
AddPrereqComponent ("MecModInterfaces"						 , Public);
AddPrereqComponent ("MechanicalModeler"			       , Public);
AddPrereqComponent ("GSMInterfaces"								 , Public);
AddPrereqComponent ("Visualization"							   , Public);
AddPrereqComponent ("CATMatInterfaces"  				   , Public);
AddPrereqComponent ("CATPlantShipInterfaces"  	   , Public);
AddPrereqComponent ("ProductStructureInterfaces"   , Public);





