
// COPYRIGHT DASSAULT SYSTEMES 2002

//=============================================================================
//
// This program reads an XML document and writes it back either in UTF-8
// or UTF-16.
//
//  Illustrates:
//     1 - How to create a DOM from an XML input file
//     2 - How to create an XML output file from a DOM
//     3 - How to customize the XML generated by the Write function 
//    
//=============================================================================

// C++ Standard library
#include <iostream.h>

// XMLParser Framework
#include "CATIXMLDOMDocumentBuilder.h"  // To create the DOM objects
#include "CATIDOMDocument.h"            // To represent an XML document in DOM form

// System Framework
#include "CATListOfCATUnicodeString.h" // To specify options to the parser
#include "CATError.h"                  // V5 error handling functions

int main(int argc, char ** argv) {

	// Make sure the input parameters are correct, otherwise display
	// the usage message.
	if (!((argc == 4) && ((strcmp(argv[1], "-utf8") == 0) || (strcmp(argv[1], "-utf16") == 0)))) {
		cerr << "Usage: CAAXMLDOMTranscode (-utf8|-utf16) <infilepath> <outfilepath>" << endl;
		return 1;
	}

	// The name of the input and output file
	CATUnicodeString inputFile = argv[2];
	CATUnicodeString outputFile = argv[3];

	// Step 1
	// Instantiate the builder. The builder knows how to create all the
	// DOM objects pertaining to a specific implementation of the
	// CAA XMLParser DOM API
	CATIXMLDOMDocumentBuilder_var builder;
	HRESULT hr = ::CreateCATIXMLDOMDocumentBuilder(builder);
	if (SUCCEEDED(hr) && (builder != NULL_var)) {

		// Step 2
		// Prepare the options to pass to the builder for reading. The parser receives
		// its options in the form of (optionName, optionValue) pairs.
		// By default, the builder attempts to validate documents. In this
		// sample, we want to turn off this feature.
		CATListOfCATUnicodeString readOptions;
		readOptions.Append("CATDoValidation");
		CATListOfCATUnicodeString readOptionValues;
		readOptionValues.Append("false");

		// Create a DOM document from the input file
		CATIDOMDocument_var document;
		hr = builder->Parse(inputFile, document, readOptions, readOptionValues);
		if (SUCCEEDED(hr) && (document != NULL_var)) {

			// Step 3
			// Prepare the options to pass to the builder for writing. The parser
			// supports generating XML documents either in UTF-8 or UTF-16
			CATListOfCATUnicodeString writeOptions;
			writeOptions.Append("CATEncoding");
			CATListOfCATUnicodeString writeOptionValues;
			if (strcmp(argv[1], "-utf8") == 0) {
				writeOptionValues.Append("UTF-8");
			} else {
				writeOptionValues.Append("UTF-16");
			}

			// Write the DOM document back to the output file
			hr = builder->WriteToFile(document, outputFile, writeOptions, writeOptionValues);
		}
	}

	// Step 4
	// Print error messages if an error has occurred
	if (FAILED(hr)) {
		CATUnicodeString message = "CAAXMLDOMTranscode has failed:\n";
		CATError* error = CATError::CATGetLastError(hr);
		if (error != NULL) {
			message.Append(error->GetNLSMessage());
			error->Release();
			error = NULL;
		}
		CATError::CATCleanLastError();
		cerr << message.ConvertToChar() << endl;
		return 1;
	}
	return 0;
}

