# COPYRIGHT DASSAULT SYSTEMES 2001
#======================================================================
# Imakefile for module CAATPESplitToolPathCommand.m 
#======================================================================
#
#  Jan 2002  Creation: Code generated by the CAA wizard 
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0FM JS0GROUP AD0XXBAS CD0FRAME CD0STWIN CATMathStream \
                   CD0VWTLB DI0STATE AC0SPBAS\
# END WIZARD EDITION ZONE

LINK_WITH = CATMathStream  $(WIZARD_LINK_MODULES) CATMathematics CATManufacturingInterfaces \
		 CATViz CATVisualization CATToolPathEditorInterfaces

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
