# COPYRIGHT DASSAULT SYSTEMES 2003
#======================================================================
# Imakefile for module CAAPstPrsConfigAddin.m
#======================================================================
#
#  Sep 2003  Creation: Code generated by the CAA wizard  avm
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
LINK_WITH = CATPrsWkbPrsConfiguration\
	    CATProductStructure1\
	    CATProductStructureInterfaces\
            CATObjectModelerBase\
	    CATObjectSpecsModeler\
	    CATVisualization\
	    CD0FRAME\
	    DI0PANV2\
	    JS0FM\
	    JS0GROUP
