# COPYRIGHT DASSAULT SYSTEMES 2002
#======================================================================
# Imakefile for module CAAPeoBasis.m
#======================================================================
#
#  May 2002  Creation: Code generated by the CAA wizard  SOC
#======================================================================
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH=	CATObjectSpecsModeler\
			CATObjectModelerBase \
			JS0GROUP Collections \
            OptimizationItf \
            MecModItf KnowledgeItf
#

