# COPYRIGHT DASSAULT SYSTEMES 2003
#======================================================================
# Imakefile for module CATV4iTstGetTubingData.m
#======================================================================
#
#  Dec 2003  Creation: Code generated by the CAA wizard  nbl
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = 
# END WIZARD EDITION ZONE

LINK_WITH =  JS0GROUP CATV4iInterface CATV4iServices \
             CATObjectModelerBase \
             CATV4iTubingServices  

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
