//------------------------------------------------------------------
// COPYRIGHT DASSAULT SYSTEMES 2006


//=============================================================================
//  Abstract of Use Case "CAABatBatchLauncherSample":
//  ------------------------------------

//=============================================================================


#include "CATBatClientMonitorCAA.h"
#include "CATBatchEventWatcher.h"
#include "CATBatchPublicDefinitions.h"
#include "CATIBatchCAA.h"
#include "CATIBatchElementCAA.h"
#include "CATIBatchElementsCAA.h"

#include "CATBatchAccessCAA.h"
#include "CATBatchParameters.h"
#include "CATBatchLogCAA.h"

#include "CATLib.h"




 
int main (int argc, char** argv)
{
	
	   //Here we generate the XML parameter file corresponding to the batch : BatchSample
	  //This file will be named ParamTest.xml and saved by default in $BATCH_HOME
	  
	  //The purpose of this file is to describe the input and the outputs of BatchSample
	  CATBatchParameters input_param;
	  input_param.BeginBuffer("BatchSample", "ParamTest.xml"); 
	  
	  //Here we describe the inputs , a set of model files
	  input_param.BeginInput();
		input_param.InsertFile("file1", "$ADL_ODT_IN/ATTRIBUTCXR1.model", "", COMM_FILE_BINARY);
		input_param.InsertFile("file2", "$ADL_ODT_IN/BOBINE.model", "", COMM_FILE_BINARY);
		input_param.InsertFile("file3", "$ADL_ODT_IN/CUBE.model", "", COMM_FILE_BINARY);
		
		//This input is flag us	able by BatchSample
		input_param.InsertSimpleArg("action", "1");
		input_param.EndInput();
		
		// Here we describe the output directory for BatchSample.
		const char* batch_home = CATGetEnv("BATCH_HOME");
		
		const char* out_folder = batch_home; // we choose to write the outputs in $BATCH_HOME. 
		
		input_param.BeginOutput();
		input_param.InsertFolder("out_dir", out_folder, "" , COMM_FILE_BINARY, "CATPart");
		input_param.EndOutput();
		input_param.EndBuffer();
	
	  //Retrieve the ClientMonitor, main interface to start and monitor batches
	  CATBatClientMonitorCAA*  cliMonitor = CATBatClientMonitorCAA::GetTheClientMonitorCAA();
	  if (!cliMonitor)	return 5;
	  
	  //We intialize the abitlity the monitor V5 batches
	  HRESULT hr = cliMonitor->InitializeV5Monitoring();
	  
	  //We need a specific object to register callbacks on batch events.
	  //Here we are interested in CATBatchEndNotif only
	  int cond_for_exit = 0; 
	  CATBatchEventWatcher evt(&cond_for_exit);
	 
	  char uuid[SIZE_T_ID];
     
     //We retrieve the full path of the previously generated XML parameter file
    CATUnicodeString path_param;
    input_param.GetFullPath(path_param);
    
    //We start the batch, uuid is an output argument retrieved by this call. It is a unique identifier for this batch run
    // It must be used later on as an input to get information on this batch execution.
		hr = cliMonitor->StartV5Batch(path_param, uuid);	 
		if (FAILED(hr))	return 10;
		
		// We tell the CATBatchEventWatcher which CATBatchEndNotif it must expect.
		evt.SetUUID(uuid);
		
		//We explicitly wait for the end of the batch, when cond_for_exit==1 the loop exits
		//It is up to CATBatchEventWatcher to set this flag to 1 when the right CATBatchEnd has been received.
		hr = cliMonitor->WaitOnMessage(cond_for_exit);
		if (FAILED(hr))	return 15;
		
		int rc = evt.GetRC(); // you can also direclty call cliMonitor->GetBatchRC(uuid, rc);
		
		//The batch has ended
		CATIBatchCAA* outputParamfile =NULL;
		if (rc==0)
		{
			// The Rc of the batch is 0, we examine the output.xml file generated by this batch and describing
			// the produced outputs.
			
			//Retrieve the output XML file of the batch by its uuid.
			//A CATIBatchCAA interface is retrieved allowing to access the XML tags of the output XML file
			// This file is located in $BATCH_HOME\uuid\output.xml where uuid is the uuid of batch
			
			hr = GetOutputXMLFile(outputParamfile, uuid);
			
			if (FAILED(hr) || !outputParamfile)	return 20;
			
		
			CATIBatchElementCAA* outputParametersSection = NULL;
		
		  //We retrieve the outputs section of the XML output file	 
      hr = outputParamfile->get_OutputParametersCAA(outputParametersSection);
      if (FAILED(hr))	return 25;
  
      //We retrieve the output file list 
      CATIBatchElementsCAA* fileList=NULL;
	    hr =  outputParametersSection->get_FileListCAA(fileList);
	    if (FAILED(hr))	return 30;
	    outputParametersSection->Release();
	       
	    CATIBatchElementCAA* elem = NULL;
	    long fileCount = 0;
			hr = fileList->get_Count(fileCount);
			if (FAILED(hr))	return 35;
			
			CATUnicodeString path;
			for ( int ii = 0; ii<fileCount; ii++ )
			{
				hr = fileList->ItemCAA( ii, elem  );
				if ( FAILED(hr) ) continue;
				elem->get_Path(path);
				
				//We dump the path of each file declared in the  output section of the output XML file
				printf("Found output <%s>\n", path.CastToCharPtr());
				elem->Release();
			  if ( FAILED(hr) ) continue;
			}
			
			fileList->Release();
						
		}
		
		
		//Clean-up (if needed)
		
	 //InputParameter file
	 CATDeleteFile(path_param.CastToCharPtr());
		
	//Log file
	CATBatchLogCAA::DeleteLogs(uuid);
	
	//Delete output
	CATUnicodeString outputXMLfile;
  hr = CATBatchParameters::GetOutputParamPath(outputXMLfile, uuid);
  if (FAILED(hr))	return 40;
  CATDeleteFile(outputXMLfile.CastToCharPtr());
		
	//Delete batch directory
	CATUnicodeString root_path;
	hr = GetBatchRootCAA(root_path, uuid);
	
	if (FAILED(hr))	return 45;
	
	CATDeleteDirectory(root_path.CastToCharPtr());
		
    return rc;
}

