// COPYRIGHT DASSAULT SYSTEMES 2007

//-------------------------------------------------- Include File of this class
#include "CAA2DLPrintToDraftingWatcher.h"

// Internal
#include "CAA2DLWindowWarning.h"

//---------------------------------------------------------------------- System
#include "CATMsgCatalog.h"
#include "CATUnicodeString.h"

//---------------------------------------------------------------------- Dialog
#include "CATDlgNotify.h"
#include "CATDlgUtility.h"

//--------------------------------------------------------- BatchInfraStructure
#include "CATBatchAccessCAA.h"
#include "CATBatchEndNotifCAA.h"
#include "CATBatchNotif.h"
#include "CATBatClientMonitorCAA.h"
#include "CATBatchLogCAA.h"
#include "CATBatchParameters.h"


CATImplementClass( CAA2DLPrintToDraftingWatcher,
                   Implementation,
                   CATBaseUnknown,
                   CATnull );



CAA2DLPrintToDraftingWatcher::CAA2DLPrintToDraftingWatcher()
{
  CATBaseUnknown* pub = GetBatchPublisherCAA();
  _CB = ::AddCallback(this, pub, CATBatchEndNotifCAA::ClassName(), 
    (CATSubscriberMethod)&CAA2DLPrintToDraftingWatcher::OnBatchEnd, NULL);
  memset(_uuid, '\0', SIZE_T_ID);
  _rc = 99;
}
CAA2DLPrintToDraftingWatcher::~CAA2DLPrintToDraftingWatcher () 
{
}
void CAA2DLPrintToDraftingWatcher::SetUUID(char* uuid)
{
  if (uuid)
    strncpy(_uuid, uuid, SIZE_T_ID);

}
void  CAA2DLPrintToDraftingWatcher::OnBatchEnd(CATCallbackEvent iEvt, void *iAlarme,
                             CATNotification  *iNotif, CATSubscriberData iDonnees,
                             CATCallback       iIdCbk)
{
  CATBatchNotif* batch_notif = (CATBatchNotif*)iNotif;
  if (!batch_notif)	return;

  char* uuid = batch_notif->GetBatchUUID();

  if (!strncmp(uuid, _uuid, SIZE_T_ID))
  {
    CATBatClientMonitorCAA* cm  = CATBatClientMonitorCAA::GetTheClientMonitorCAA();
    if (!cm)	return;

    CATBatchStatus status;
    HRESULT hr = cm->GetBatchStatus(uuid, status);
    if (FAILED(hr))	return;
    hr = cm->GetBatchRC(uuid, _rc);

    // Get the trace activation
    const char* ctraceActivation = CATGetEnv("CAT_CAA2DL_TRACES");
    if (!ctraceActivation)
    {
      // Clean up the log generated by the batch
      //Retrieve the output XML file of the batch by its uuid.
      CATBatchLogCAA::DeleteLogs(uuid);

      CATUnicodeString outputXMLfile;
      if (SUCCEEDED(CATBatchParameters::GetOutputParamPath(outputXMLfile, uuid)))
        CATDeleteFile(outputXMLfile.CastToCharPtr());

      CATUnicodeString root_path;
      if (SUCCEEDED(GetBatchRootCAA(root_path, uuid)))
        CATDeleteDirectory(root_path.CastToCharPtr());
    }
    // Display the batch report window:
    CATDlgNotify *pBox = NULL;
    if (0 == _rc)
    {
      CATUnicodeString sMsg = CATMsgCatalog::BuildMessage( "CAA2DLPrintToDrafting","BatchEnded");
      pBox = CAA2DLWindowCreateMsgBox( "BatchEnded", sMsg, CATDlgNfyInformation );
    }
    else if (74 == _rc)
    {
      CATUnicodeString sMsg = CATMsgCatalog::BuildMessage( "CAA2DLPrintToDrafting","CompatibleStd");
      pBox = CAA2DLWindowCreateMsgBox( "CompatibleStd", sMsg, CATDlgNfyInformation );
    }
    else if (75 == _rc)
    {
      CATUnicodeString sMsg = CATMsgCatalog::BuildMessage( "CAA2DLPrintToDrafting","PsGeneration");
      pBox = CAA2DLWindowCreateMsgBox( "PsGeneration", sMsg, CATDlgNfyInformation );
    }
    else if (76 == _rc)
    {
      CATUnicodeString sMsg = CATMsgCatalog::BuildMessage( "CAA2DLPrintToDrafting","PsPrinting");
      pBox = CAA2DLWindowCreateMsgBox( "PsPrinting", sMsg, CATDlgNfyInformation );
    }
    else
    {
      CATUnicodeString sMsg = CATMsgCatalog::BuildMessage( "CAA2DLPrintToDrafting","batchEnv");
      pBox = CAA2DLWindowCreateMsgBox( "batchEnv", sMsg, CATDlgNfyInformation );
    }

    CATUnicodeString sMsgTitle = CATMsgCatalog::BuildMessage( "CAA2DLPrintToDrafting","BatchReport");
    if (pBox) pBox->SetTitle(sMsgTitle);

    CATBaseUnknown* pub = GetBatchPublisherCAA();
    // ::RemoveCallback(this,pub,_CB);
    if (FAILED(hr))	return;
  }
}
