// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CAAPuiPRDWorkshopAddin.h
// Provide implementation to interface
//    CATIPRDWorkshopAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Aug 2003  Creation: Code generated by the CAA wizard  avm
//===================================================================
#ifndef CAAPuiPRDWorkshopAddin_H
#define CAAPuiPRDWorkshopAddin_H

#include "CATBaseUnknown.h"

//-----------------------------------------------------------------------

/**
 * Class Object modeler implementation class.
 * <br>
 * It implements the interface:
 *  <ol>
 *  <li>CATIPRDWorkshopAddin @see ApplicationFrame.CATIWorkbenchAddin
 *  </ol>
 */
class CATCmdContainer;

class CAAPuiPRDWorkshopAddin: public CATBaseUnknown {

CATDeclareClass;

public:

	// Standard constructors and destructors for an implementation class
	// -----------------------------------------------------------------
	CAAPuiPRDWorkshopAddin();
	virtual ~CAAPuiPRDWorkshopAddin();

	/**
	 * @see ApplicationFrame.CATIWorkbenchAddin#CreateCommands
	 */
	void CreateCommands();

	/**
	 * @see ApplicationFrame.CATIWorkbenchAddin#CreateToolbars
	 */
	CATCmdContainer * CreateToolbars();


private:
	// The copy constructor and the equal operator must not be implemented
	// -------------------------------------------------------------------
	CAAPuiPRDWorkshopAddin(CAAPuiPRDWorkshopAddin &);
	CAAPuiPRDWorkshopAddin& operator=(CAAPuiPRDWorkshopAddin&);

};

//-----------------------------------------------------------------------

#endif
