// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CAAPuiPRDWorkshopAddinCmd.h
// The command: CAAPuiPRDWorkshopAddinCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Aug 2003  Creation: Code generated by the CAA wizard  avm
//===================================================================
#ifndef CAAPuiPRDWorkshopAddinCmd_H
#define CAAPuiPRDWorkshopAddinCmd_H

#include "CATCommand.h"

//----------------------------------------------------------------------

/**
 * Command for the CAAPuiPRDWorkshopAddin use case
 */
class CAAPuiPRDWorkshopAddinCmd: public CATCommand {

public:

	CAAPuiPRDWorkshopAddinCmd();
	virtual ~CAAPuiPRDWorkshopAddinCmd();

	/**
	 * Activates our command.
	 * @param iFromClient 
	 *   The command that requests to activate the current one.
	 * @param iEvtDat
	 *   The notification sent.
	 */
	virtual CATStatusChangeRC Activate(CATCommand * iFromClient,
					   CATNotification * iEvtDat);
};

//----------------------------------------------------------------------

#endif
