# COPYRIGHT DASSAULT SYSTEMES 1994-2000
#======================================================================
# Imakefile for module CAAOmmProIdl.m
# Module for compilation of the protected IDL interfaces
#======================================================================
#
#  Jan 2000  Creation: Code generated by the CAA wizard  LLE
#======================================================================
#
# NO BUILD           
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

SOURCES_PATH=ProtectedInterfaces
COMPILATION_IDL=YES

LINK_WITH=JS0GROUP \
          CATMecModInterfaces
