// COPYRIGHT DASSAULT SYSTEMES 2002
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework CAABehavorInterfaces.edu
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Oct 2002  Creation: Code generated by the CAA wizard  jpi
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
// END WIZARD EDITION ZONE
