# COPYRIGHT DASSAULT SYSTEMES 1994-2000
#======================================================================
# Imakefile for module CAAOmmTypeLib.m
# Module for compilation of the typelib
#======================================================================
#
#  Jan 2000  Creation: Code generated by the CAA wizard  LLE
#======================================================================
#
# TYPELIB          
#

BUILT_OBJECT_TYPE=TYPELIB
# no more BUILD_PRIORITY=40

LINK_WITH = InfTypeLib MecModTypeLib


