// COPYRIGHT Dassault Systemes 2005
//===================================================================
//
// CAAUipFilteringCriteriaExt.cpp
// Provide implementation to interface
//    CATIEleUipFilteringCriteria
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Jun 2002  Creation: Code generated by the CAA wizard  LVT
//===================================================================
#include "CAAUipFilteringCriteriaExt.h"

#include "CATListOfCATUnicodeString.h"
#include "CATUnicodeString.h"

// Tie the implementation to its interface
// ---------------------------------------
#include "TIE_CATIEleUipFilteringCriteria.h"
TIE_CATIEleUipFilteringCriteria( CAAUipFilteringCriteriaExt);

#include "TIE_CATIEleUipSystems.h"
TIE_CATIEleUipSystems( CAAUipFilteringCriteriaExt);


CATImplementClass(CAAUipFilteringCriteriaExt, DataExtension, CATBaseUnknown, CATElecSoftwareOpennessImpl);

//-----------------------------------------------------------------------------
// CAAUipFilteringCriteriaExt : constructor
//-----------------------------------------------------------------------------
CAAUipFilteringCriteriaExt::CAAUipFilteringCriteriaExt():
CATBaseUnknown()
	{
	}

//-----------------------------------------------------------------------------
// CAAUipFilteringCriteriaExt : destructor
//-----------------------------------------------------------------------------
CAAUipFilteringCriteriaExt::~CAAUipFilteringCriteriaExt()
	{
	}

//-----------------------------------------------------------------------------
// Implements CATIEleUipFilteringCriteria::ListCriteria
//-----------------------------------------------------------------------------
HRESULT CAAUipFilteringCriteriaExt::ListCriteria (const CATListValCATUnicodeString * iListOfSystems , CATListValCATUnicodeString *& oListOfCriteria)
	{
	oListOfCriteria = new CATListOfCATUnicodeString();

	if (oListOfCriteria) 
		{
		oListOfCriteria -> Append(CATUnicodeString("FULL"));
		oListOfCriteria -> Append(CATUnicodeString("CRIT1"));
		oListOfCriteria -> Append(CATUnicodeString("CRIT2"));
		}
	return S_OK;
	}

//-----------------------------------------------------------------------------
// Implements CATIEleUipFilteringCriteria::ListWires
//-----------------------------------------------------------------------------
HRESULT CAAUipFilteringCriteriaExt::ListWires (const CATListValCATUnicodeString * iListOfSystems , const CATListValCATUnicodeString * iListOfCriteria , CATListValCATUnicodeString *& oListOfWires)
	{
	CATUnicodeString Criteria;
	if (iListOfCriteria && iListOfCriteria -> Size() > 0)Criteria = (*iListOfCriteria)[1];
	else return E_FAIL;

	oListOfWires = new CATListValCATUnicodeString();
	if (oListOfWires)
		{
		if (Criteria == "FULL")
			{
			oListOfWires -> Append(CATUnicodeString("Wire1"));
			oListOfWires -> Append(CATUnicodeString("Wire2"));
			oListOfWires -> Append(CATUnicodeString("Wire3"));
			oListOfWires -> Append(CATUnicodeString("Wire4"));
			oListOfWires -> Append(CATUnicodeString("Wire5"));
			oListOfWires -> Append(CATUnicodeString("Wire6"));
			oListOfWires -> Append(CATUnicodeString("Wire7"));
			}
		else if (Criteria == "CRIT1")
			{
			oListOfWires -> Append(CATUnicodeString("Wire1"));
			oListOfWires -> Append(CATUnicodeString("Wire3"));
			oListOfWires -> Append(CATUnicodeString("Wire5"));
			}
		else if (Criteria == "CRIT2")
			{
			oListOfWires -> Append(CATUnicodeString("Wire1"));
			oListOfWires -> Append(CATUnicodeString("Wire4"));
			oListOfWires -> Append(CATUnicodeString("Wire5"));
			oListOfWires -> Append(CATUnicodeString("Wire6"));
			oListOfWires -> Append(CATUnicodeString("Wire7"));
			}
		else return E_FAIL;
		}
	return S_OK;
	}
//-----------------------------------------------------------------------------
// Implements CATIEleUipSystems::ListSystems
//-----------------------------------------------------------------------------
HRESULT CAAUipFilteringCriteriaExt::ListSystems (CATListValCATUnicodeString *& oListOfSystems)
	{
	oListOfSystems = new CATListOfCATUnicodeString();

	if (oListOfSystems) 
		{
		oListOfSystems -> Append(CATUnicodeString("SAMPLE"));
		}
	return S_OK;
	}
