# COPYRIGHT DASSAULT SYSTEMES 2000
#
# LOAD MODULE for CAADlgBBSender.m
#

BUILT_OBJECT_TYPE = LOAD MODULE

LINK_WITH  = JS0GROUP JS0FM CATSysCommunication DI0PANV2 CAADlgBBMessageInt

OS = Windows_NT 
MKMFC_DEPENDENCY = yes
LOCAL_LDFLAGS = $(SUB_WIN)

OS = SunOS
SYS_LIBS = -lXm -lXt -lX11
