// COPYRIGHT Dassault Systemes 2001
//===================================================================
//
// CAAETstAddin.h
// Provide implementation to interface
//    CATIPrtCfgAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   EXTENSION: TSTPartAddin
//   TIE: CATIPrtCfgAddin
//End CAA2 Wizard Generation Report
//
//  Jul 2001  Creation: Code generated by the CAA wizard  XBT
//===================================================================
#ifndef CAAEGsiFeaturesSplAddin_H
#define CAAEGsiFeaturesSplAddin_H

#include "CATBaseUnknown.h"
class CATCmdContainer;
//-----------------------------------------------------------------------

/**
 * Class Class extending the object "TSTPartAddin".
 * <br>
 * It implements the interfaces :
 *  <ol>
 *  <li>@see PartInterfaces.CATIPrtCfgAddin
 *  </ol>
 * Using this prefered syntax will enable mkdoc to document your class.
 */
class CAAEGsiFeaturesSplAddin: public CATBaseUnknown
{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     CAAEGsiFeaturesSplAddin ();
     virtual ~CAAEGsiFeaturesSplAddin ();

     CATCmdContainer* CreateToolbars();
    void CreateCommands();


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  CAAEGsiFeaturesSplAddin (CAAEGsiFeaturesSplAddin &);
  CAAEGsiFeaturesSplAddin& operator=(CAAEGsiFeaturesSplAddin&);

};

//-----------------------------------------------------------------------

#endif
