# COPYRIGHT DASSAULT SYSTEMES 2004
#======================================================================
# Imakefile for module CAALifTestIntegrateKnowledge.m
#======================================================================
#
#  June 2004  Creation: Code generated by the CAA wizard  aal
#======================================================================

#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE = LOAD MODULE
PROGRAM_NAME = CAALifTestIntegrateKnowledge
LINK_WITH = JS0GROUP KnowledgeItf CAALifBasis AC0SPBAS AC0DOMAIN

