# COPYRIGHT DASSAULT SYSTEMES 2003
#======================================================================
# Imakefile for module CAAPstPRDWksAdn.m
#======================================================================
#
#  Aug 2003  Creation: Code generated by the CAA wizard  avm
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
LINK_WITH = CATPrsWksPRDWorkshop CD0VWTLB JS0FM JS0GROUP DI0PANV2

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
