# COPYRIGHT DASSAULT SYSTEMES 1999
#
# CATDlgBurger LOAD MODULE
#

BUILT_OBJECT_TYPE=LOAD MODULE

LINK_WITH = DI0PANV2 \
            JS0FM  JS0GROUP 

OS = Windows_NT 
MKMFC_DEPENDENCY = yes
LOCAL_LDFLAGS = $(SUB_WIN)            

OS = SunOS
SYS_LIBS = -lXm -lXt -lX11
