# COPYRIGHT DASSAULT SYSTEMES 2003
#======================================================================
# Imakefile for module CAAPstProductInSession.m
#======================================================================
#
#  Aug 2003  Creation: Code generated by the CAA wizard  rid
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) \
			CATProductStructure1 \
			CATObjectModelerBase \
            JS0GROUP \
			JS0CORBA \
            CATObjectSpecsModeler

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
