# COPYRIGHT DASSAULT SYSTEMES 2000
#
# LOAD MODULE
#

BUILT_OBJECT_TYPE = LOAD MODULE

# requests : Dialog   System
LINK_WITH  = DI0PANV2 JS0FM JS0GROUP

OS = Windows_NT
MKMFC_DEPENDENCY = yes
LOCAL_LDFLAGS = $(SUB_WIN)
