# COPYRIGHT DASSAULT SYSTEMES 2000

#
# LOAD MODULE for CAADlgHelloApplication.m
#

BUILT_OBJECT_TYPE = LOAD MODULE

LINK_WITH  = JS0GROUP DI0PANV2 JS0FM

OS = Windows_NT 
MKMFC_DEPENDENCY = yes
LOCAL_LDFLAGS = $(SUB_WIN)

OS = SunOS
SYS_LIBS = -lXm -lXt -lX11

