// COPYRIGHT Dassault Systemes 2012
//===================================================================
//
// CAAV5V6MmrPartWksFreezeUnfreezeCmd.h
// The state chart based command: CAAV5V6MmrPartWksFreezeUnfreezeCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA Wizard Generation Report
//   STATECOMMAND
//End CAA Wizard Generation Report
//
//  May 2007  Creation: Code generated by the CAA wizard  GRO
//===================================================================
#ifndef CAAV5V6MmrPartWksFreezeUnfreezeCmd_H
#define CAAV5V6MmrPartWksFreezeUnfreezeCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"

class CATPathElementAgent;
//CAA WIZARD FORWARD DECLARATION SECTION: DO NOT EDIT
//END CAA WIZARD FORWARD DECLARATION SECTION

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class CAAV5V6MmrPartWksFreezeUnfreezeCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( CAAV5V6MmrPartWksFreezeUnfreezeCmd, CATStateCommand )

  public:

  CAAV5V6MmrPartWksFreezeUnfreezeCmd();
  virtual ~CAAV5V6MmrPartWksFreezeUnfreezeCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

   CATBoolean FreezeOrUnfreeze(void* iData);

  private:
	  CATPathElementAgent* _daObjectToSelect;
};

//----------------------------------------------------------------------

#endif
