// COPYRIGHT Dassault Systemes 2001
//===================================================================
//
// CAAETstAddin.cpp
// Provide implementation to interface
//    CATIPrtCfgAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Jul 2001  Creation: Code generated by the CAA wizard  XBT
//===================================================================
//
// --------------------------------------------------------------------------------
// IMPORTANT NOTE 
// To access to the command (Toolbar displayed in ShapeDesignWorkbench)  : 
// 1/ in dictionnary CAAGSMInterfaces.edu\CNext\code\dictionnary\CAAGSMInterfaces.edu.dico 
// Un-comment the line the following line 
//CAAGsiSplAddin	  CATIShapeDesignWorkshopAddin	libCAAGsiFeaturesSplAddin
// 2/ redo the runtime view (mkrtv) 
// --------------------------------------------------------------------------------
// 

#include "CAAEGsiFeaturesSplAddin.h"
#include "CATCmdContainer.h"
#include "CATCreateWorkshop.h" // needed to manage workshop access
#include "CATCommandHeader.h"  // needed to instanciate the header



MacDeclareHeader(CAAGsiFeaturesSplCommandHeader);  

CATImplementClass( CAAEGsiFeaturesSplAddin, DataExtension, CATBaseUnknown, CAAGsiSplAddin );
 
//-----------------------------------------------------------------------------
// CAAETstAddin : constructor
//-----------------------------------------------------------------------------
CAAEGsiFeaturesSplAddin::CAAEGsiFeaturesSplAddin():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// CAAETstAddin : destructor
//-----------------------------------------------------------------------------
CAAEGsiFeaturesSplAddin::~CAAEGsiFeaturesSplAddin()
{
}
 
// Tie the implementation to its interface
// ---------------------------------------
#include "TIE_CATIShapeDesignWorkshopAddin.h"
TIE_CATIShapeDesignWorkshopAddin( CAAEGsiFeaturesSplAddin);

void CAAEGsiFeaturesSplAddin::CreateCommands()
{
    

    // Instantiation of the header class created by the macro MacDeclareHeader -
    // commands are always available and are represented by a push button
    
    //command for edit sketch
    new CAAGsiFeaturesSplCommandHeader( "CAAGSMSewSkinBasicHdr"   ,            // Header Name 
									 "CAAGsiFeaturesSplSewSkinBasicUI"    ,       // Module name 
									 "CAAGSMSewSkinBasicCmd" ,                 // Cmfd name   
									 (void *)NULL           );
    new CAAGsiFeaturesSplCommandHeader( "CAAGSMCircleSweepTgHdr"   ,           // Header Name 
									 "CAAGsiFeaturesSplCircleSweepTgUI"    ,      // Module name 
									 "CAAGSMCircleSweepTgCmd" ,                // Cmfd name   
									 (void *)NULL              );

}


//-----------------------------------------------------------------------------
// Implements CATIWorkbenchAddin::CreateToolbars
//-----------------------------------------------------------------------------

CATCmdContainer* CAAEGsiFeaturesSplAddin::CreateToolbars()
{
 


	    // cout << "(CAAEMmrSettingsAddIn::CreateToolbars)"<< endl;
    //----------------------
    // SewSkin Toolbar
    //----------------------
    NewAccess        ( CATCmdContainer  , pCaaCmdSplTlb , CAATstSewSkinTlb );
   
      NewAccess        ( CATCmdStarter    , pCAASewSkinBasicT    , CAASewSkinBasicStr );
      SetAccessCommand ( pCAASewSkinBasicT    , "CAAGSMSewSkinBasicHdr" );
      SetAccessChild   ( pCaaCmdSplTlb , pCAASewSkinBasicT  );
   
      NewAccess        ( CATCmdStarter    , pCAACircleSweepTgT    , CAACircleSweepTgStr );
      SetAccessCommand ( pCAACircleSweepTgT    , "CAAGSMCircleSweepTgHdr" );
      SetAccessNext    (pCAASewSkinBasicT, pCAACircleSweepTgT  );

   //----------------------
   // SewSkin  Menubar 
   //----------------------
	NewAccess(CATCmdContainer,pCaaCmdSplMbr,CAACaaCmdSplMbr);

   //  menu Tools A new command / Locate in Insert Mnu (CATAfrInsertMnu)
   //------------------------------------------------------
      NewAccess(CATCmdContainer,pTstGsiFeatMnu,CATAfrInsertMnu);
      SetAccessChild(pCaaCmdSplMbr,pTstGsiFeatMnu);

      NewAccess(CATCmdSeparator,pTstGsiFeatSep,CAATstGsiSep);
      SetAccessChild(pTstGsiFeatMnu,pTstGsiFeatSep);

      NewAccess(CATCmdStarter,  pCAASewSkinBasicM    , CAASewSkinBasicStr);
      SetAccessCommand ( pCAASewSkinBasicM    , "CAAGSMSewSkinBasicHdr" );
      SetAccessNext(pTstGsiFeatSep,pCAASewSkinBasicM);

      NewAccess(CATCmdStarter,  pCAACircleSweepTgM    , CAACircleSweepTgStr);
      SetAccessCommand ( pCAACircleSweepTgM    , "CAAGSMCircleSweepTgHdr" );
      SetAccessNext(pCAASewSkinBasicM,pCAACircleSweepTgM);


         
    SetAddinMenu(pCaaCmdSplTlb,pCaaCmdSplMbr);

  
   
      
       //----------------------
       // Visibility 
       //----------------------
       
    AddToolbarView   ( pCaaCmdSplTlb , 1 , Left ); // 1 for visible toolbar
    
    return pCaaCmdSplTlb;
    
}
