// COPYRIGHT Dassault Systemes 2007
  //===================================================================
  //
  // CAACATPDMAllowLoad.h
  // Provide implementation to interface
  //    CATIPDMUEAllowDocumentLoading
  
  //
  //===================================================================
  //
  // Usage notes:
  //
  //===================================================================
  //CAA2 Wizard Generation Report
  //EXTENSION:	VPM1_AllowDocLoad
  //EXTENSIONTYPE:	DataExtension
  
  //    TIEChain: CATIPDMUEAllowDocumentLoading
  
  //End CAA2 Wizard Generation Report
  //
  //  Jan 2007  Creation: Code generated by the CAA wizard  KUI
  //===================================================================
  
  #ifndef CAACATPDMAllowLoad_H
  #define CAACATPDMAllowLoad_H
  
  #include "CATBaseUnknown.h"
  #include "CATIDocId.h"
  
  /**
  * Class representing xxx.
  *
  * <br><b>Role</b>: Provide the basic class function...
  * <p>
  * It implements the interfaces :CATIPDMUEAllowDocumentLoading
  *  <ol>
  *  <li>@href
  *  </ol>
  *
  * @href ClassReference, Class#MethodReference, #InternalMethod...
  */
  
  class CAACATPDMAllowLoad : public CATBaseUnknown
  
  {
    CATDeclareClass;
  
    public:
  
    // Standard constructors and destructors for an implementation class
    // -----------------------------------------------------------------
       CAACATPDMAllowLoad();
       virtual ~CAACATPDMAllowLoad();
       
       /**
       * Implements a function from an interface.
       * @href CATIPDMUEAllowDocumentLoading#AllowDocumentLoading
       */
       HRESULT AllowDocumentLoading(int iNbDocs, CATIDocId **iListDocIds, double **ipDocSize);
       
   };
   
   #endif
   
