/**
* @quickReview AJD 06:01:24
* @fullReview SOU AJD 06:01:10
*/
//=============================================================================
// COPYRIGHT DASSAULT SYSTEMES  2006
//
// Sample code for : TopReflectLine operator
// Mission         : Explains how to create both conical as well as cylindrical CATTopReflectLine operator
//           
// Type            : Batch program
// Inputs          : None
// Outputs         : Return codes (if not null, the model is not saved)
//                   0- OK
//                   1 - KO
//
// Main steps        1- Create the geometry factory and other preliminary operations
//                   2- Create the profile for tabulated cylinder
//                   3- Create the tabulated cylinder
//                   4- Create the skin from tabulated cylinder
//                   5- Create origin point & body for conical reflect line 
//                   6- Create conical reflect line, with 140 degree angle
//                   8- Clean the no longer wanted objects 
//                   9- Write the model and close the container  
//
// How to run it   : CAATopReflectLine   // to run whithout storing the NCGM file
//                   CAATopReflectLine FileName.NCGM // to run and store the result in FileName.NCGM     
//==================================================================

#include <iostream.h>
#include <iomanip.h>
#include "fstream.h"

// Mathematics
#include "CATMathDirection.h"                // Mathematical direction
#include "CATMathConstant.h"

// Advanced Mathematics
#include "CATMathSetOfPointsND.h"        // Creation of a set of points
#include "CATSoftwareConfiguration.h"

// GeometricObjects
#include "CATGeoFactory.h"               // Geometry factory
#include "CATCGMContainerMngt.h"         // Management of the geometry factory
#include "CATSplineCurve.h"              // Spline creation
#include "CATTabulatedCylinder.h"
#include "CATCartesianPoint.h"

// TopologicalOperators
#include "CATTopVertex.h"
#include "CATTopSkin.h"
#include "CATCreateTopReflectLine.h"
#include "CATTopReflectLine.h"

// NewTopologicalObjects
#include "CATBody.h"                     // Body


// ---------------------------------------------------------------------------
int main(int    iArgc,   // Number of arguments (0) or (1) 
         char** iArgv)   // Path to the *.NCGM document generated by this program
{
    int rc = 0;
    
    if( 2 < iArgc) 
    {
      cout << "Invalid number of arguments " << endl;
      cout << "Usage : CAATopReflectLine [FileName.NCGM] " << endl;
      return (1);
    }
    
    char *pFileName = 0;
    int  toStore = 0;
    if (2 == iArgc) 
    {
        toStore = 1; 
        pFileName = iArgv[1];
    }
    
    //----------------------------------------------------------------------------
    // 1 - Create the geometry factory and other preliminary operations
    //----------------------------------------------------------------------------
    //
    // a - Factory 
    //
    CATGeoFactory* pGeomFactory = ::CATCreateCGMContainer() ;
    if ( 0 == pGeomFactory ) 
    {
      cout << "Factory creation failed, exiting !!! " << endl;
      return (1);
    }
    cout << "1. Factory creation OK" << endl;
    
    // b - Configuration
    //
    CATSoftwareConfiguration * pConfig = new CATSoftwareConfiguration();
    CATTopData topdata(pConfig, NULL);
    
    // -----------------------------------------------------------------------------
    // 2 - Create the profile for tabulated cylinder
    // -----------------------------------------------------------------------------

    CATMathSetOfPointsND pointSet1(3,6);  // set of points for profile 1
        
    double Point1[3]={ 0., 10., 0.} ;
    double Point2[3]={ 10., 2., 0.} ;
    double Point3[3]={ 15., 17., 0.} ;
    double Point4[3]={ 20., 20., 0.} ;
    double Point5[3]={ 25., 17., 0.} ;
    double Point6[3]={ 30., 0., 0.} ;

    pointSet1.AddPoint(Point6); //the order of points affects the surface normal
    pointSet1.AddPoint(Point5); 
    pointSet1.AddPoint(Point4); 
    pointSet1.AddPoint(Point3); 
    pointSet1.AddPoint(Point2); 
    pointSet1.AddPoint(Point1); 

    CATSplineCurve * pProfile = pGeomFactory->CreateSplineCurve(&pointSet1,0,1,2,0);
    if ( 0 == pProfile)
    {
        ::CATCloseCGMContainer(pGeomFactory);
        cout << "Profile creation for tabulated cylinder failed, exiting !!! " << endl;
        return (1);
    }

    cout << "2. Profile for tabulated cylinder creation OK" << endl;

    // -----------------------------------------------------------------------------
    // 3 - Create the tabulated cylinder
    // -----------------------------------------------------------------------------
    CATMathDirection cylAxis;
    cylAxis.SetCoord(0.,0.,1.);

    //first surface
    CATTabulatedCylinder * pTabCylinder = pGeomFactory->CreateTabulatedCylinder( pProfile, cylAxis, 0., 20.);
    if ( 0 == pTabCylinder )
    {
        ::CATCloseCGMContainer(pGeomFactory);
        cout << "Tabulated cylinder creation failed, exiting !!! " << endl;
        return (1);
    }
    
    cout << "3. Tabulated cylinder creation OK" << endl;

    // -----------------------------------------------------------------------------
    // 4 - Create the skin from tabulated cylinder
    // -----------------------------------------------------------------------------

    //first skin
    CATSurLimits surLim1;
    pTabCylinder->GetLimits(surLim1); 

    CATTopSkin * pSkinOp =  CATCreateTopSkin( pGeomFactory , 
                                              &topdata,
                                              pTabCylinder,   
                                              &surLim1);

    if ( 0 == pSkinOp )
    {
        ::CATCloseCGMContainer(pGeomFactory);
        cout << "Skin operator creation failed, exiting !!! " << endl;
        return (1);
    }
  
    pSkinOp->Run();

    CATBody * pSkin = pSkinOp->GetResult();

    delete pSkinOp ;
    pSkinOp = 0;

    if ( 0 == pSkin )
    {
        ::CATCloseCGMContainer(pGeomFactory);
        cout << "Skin creation failed, exiting !!! " << endl;
        return (1);
    }   

    cout << "4. Skin from tabulated cylinder creation OK" << endl;

    // -----------------------------------------------------------------------------
    // 5 - Create origin point & body for conical reflect line
    // -----------------------------------------------------------------------------
    CATPoint *pOriginPoint = pGeomFactory->CreateCartesianPoint( 0, 0, 0);

    if ( 0 == pOriginPoint )
    {
        ::CATCloseCGMContainer(pGeomFactory);
        cout << "Origin point creation failed, exiting !!! " << endl;
        return (1);
    }

    CATTopVertex *pVertexOp = CATCreateTopVertex( pGeomFactory, &topdata, pOriginPoint);
    if ( 0 == pVertexOp )
    {
        ::CATCloseCGMContainer(pGeomFactory);
        cout << "Origin body operator creation failed, exiting !!! " << endl;
        return (1);
    }
    
    pVertexOp->Run();

    CATBody * pOriginBody = pVertexOp->GetResult();

    delete pVertexOp ;
    pVertexOp = 0;

    if ( 0 == pOriginBody )
    {
        ::CATCloseCGMContainer(pGeomFactory);
        cout << "Origin body  creation failed, exiting !!! " << endl;
        return (1);
    }   

    cout << "5. Origin point/body creation for conical reflect line OK" << endl;

    // -----------------------------------------------------------------------------
    // 6 - Create conical reflect line, with 140 degree angle
    // -----------------------------------------------------------------------------
    CATTopReflectLine *pConicalReflectLineOp = CATCreateTopReflectLine( pGeomFactory, &topdata, pSkin, pOriginBody, 140*CATDegreeToRadian);
    if ( 0 == pConicalReflectLineOp )
    {
        ::CATCloseCGMContainer(pGeomFactory);
        cout << "Conical reflect line operator creation failed, exiting !!! " << endl;
        return (1);
    }
    
    pConicalReflectLineOp->Run();

    CATBody * pConicalReflectLineBody = pConicalReflectLineOp->GetResult();

    delete pConicalReflectLineOp ;
    pConicalReflectLineOp = 0;

    if ( 0 == pConicalReflectLineBody )
    {
        ::CATCloseCGMContainer(pGeomFactory);
        cout << "Conical reflect line creation failed, exiting !!! " << endl;
        return (1);
    } 
    
    cout << "6. Conical reflect line operator OK" << endl;

    // -----------------------------------------------------------------------------
    // 7 - Create cylindrical reflect line, with 40 degree angle with x axis
    // -----------------------------------------------------------------------------
    CATMathDirection ReflectDir( 1, 0, 0);
    CATTopReflectLine *pCylReflectLineOp = CATCreateTopReflectLine( pGeomFactory, pSkin, ReflectDir, 40*CATDegreeToRadian, &topdata);
    if ( 0 == pCylReflectLineOp )
    {
        ::CATCloseCGMContainer(pGeomFactory);
        cout << "Cylindrical reflect line operator creation failed, exiting !!! " << endl;
        return (1);
    }
    
    pCylReflectLineOp->Run();

    CATBody * pCylReflectLineBody = pCylReflectLineOp->GetResult();

    delete pCylReflectLineOp ;
    pCylReflectLineOp = 0;

    if ( 0 == pCylReflectLineBody )
    {
        ::CATCloseCGMContainer(pGeomFactory);
        cout << "Cylindrical reflect line creation failed, exiting !!! " << endl;
        return (1);
    } 
    
    cout << "7. Cylindrical reflect line operator OK" << endl;

    // -----------------------------------------------------------------------------
    // 8 - Cleaning operations
    // -----------------------------------------------------------------------------
    
    pGeomFactory->Remove(pProfile);
    pGeomFactory->Remove(pTabCylinder);
    pGeomFactory->Remove(pOriginPoint);
    
    pConfig->Release();
    
    cout << "8. Factory cleaning operation OK" << endl;

    //----------------------------------------------------------------------------
    // 9 - Save the model
    //----------------------------------------------------------------------------
    
    if( 1 == toStore)
    {
        
#ifdef _WINDOWS_SOURCE
        ofstream filetowrite(pFileName, ios::binary ) ;
#else
        ofstream filetowrite(pFileName,ios::out,filebuf::openprot) ;
#endif
        
        ::CATSaveCGMContainer(pGeomFactory,filetowrite);
        filetowrite.close();
        cout << "9. Saving of NCGM file OK" << endl;
    }	
    
    ::CATCloseCGMContainer(pGeomFactory);
    cout << "All Done!" << endl;
    return (rc);
}


