# COPYRIGHT DASSAULT SYSTEMES 2003
#======================================================================
# Imakefile for module CAAPstPRDWksConfigWkb.m
#======================================================================
#
#  Sep 2003  Creation: Code generated by the CAA wizard  avm
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
LINK_WITH = CD0FRAME DI0PANV2 AD0XXBAS CATPrsWksPRDWorkshop JS0FM JS0GROUP

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
