// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CAAPstProductFileSelection.cpp
// Provide implementation to interface
//    CATIProductFileSelection
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Aug 2003  Creation: Code generated by the CAA wizard  sxy
//===================================================================
#include "CAAPstProductFileSelection.h"
#include "CAAPstProductFileSelectionTrace.h"
#include "CATUnicodeString.h"
#include "CATListOfCATUnicodeString.h"

// ObjectModelerBase prereq
#include "CATDocument.h"
#include "CATDocumentServices.h"
#include "CATIDocRoots.h"
#include "CATLISTV_CATBaseUnknown.h"
  
// ProductStructure
#include "CATIProduct.h"
#include "CATIProductSelection.h"
#include "CATIProductFileSelection.h"
#include "CATPrdCommonFileSelection.h"

// Tie the implementation to its interface
// ---------------------------------------
#include "TIE_CATIProductFileSelection.h"
TIEchain_CATIProductFileSelection(CAAPstProductFileSelection);

CATImplementClass(CAAPstProductFileSelection,
                  DataExtension,
		  CATBaseUnknown,
		  CAAPstPrdFileSel);

//-----------------------------------------------------------------------------
// Constructor
//-----------------------------------------------------------------------------
CAAPstProductFileSelection::CAAPstProductFileSelection():
	CATPrdCommonFileSelection()
{
	CAAPstPFSTRACE("CAAPstProductFileSelection - Constructor");

	_typesList = new CATListOfCATUnicodeString(1);
	if (NULL != _typesList) {
		// must be identical to the one in CAApstPrdFileSel.CATRsc
		_typesList->Append("CAAProduct");
	}
}

//-----------------------------------------------------------------------------
// Destructor
//-----------------------------------------------------------------------------
CAAPstProductFileSelection::~CAAPstProductFileSelection()
{
	CAAPstPFSTRACE("CAAPstProductFileSelection - Destructor");

	if (NULL != _typesList) {
		delete _typesList;
		_typesList = NULL;
	}
}
 
//-----------------------------------------------------------------------------
// ExtractProducts
//-----------------------------------------------------------------------------
HRESULT CAAPstProductFileSelection::ExtractProducts
	(CATIContainer* iContainer, 		// container of parent product
	 CATIProduct* iParentProduct, 		// parent product to insert to
	 CATListValCATBaseUnknown_var*& oList)	// products to be inserted
{
	HRESULT rc;
	CAAPstPFSTRACE("Entering CAAPstProductFileSelection::ExtractProducts");
	
	if (NULL == _pathsList || NULL == iContainer || NULL == iParentProduct)
		return E_FAIL;
	int pathCount = _pathsList->Size();
	if (NULL == oList) {
		// allocate product list
		oList = new CATLISTV(CATBaseUnknown_var) (pathCount);
		if (NULL == oList) {
			CAAPstPFSTRACE("Failed to allocate output list");
			return E_FAIL;
		}
	}

	for (int pathNum = 1; pathNum <= pathCount; pathNum++) {

		//
		// For each file selected,
		// retrieve the 2nd child product for insertion
		//
		CATUnicodeString& curPath = (*_pathsList)[pathNum];
		CATDocument* pSelectedDoc = NULL;
		rc = CATDocumentServices::OpenDocument(curPath, pSelectedDoc);
		if (FAILED(rc) || NULL == pSelectedDoc) {
			CAAPstPFSTRACE("Failed to open selected document");
			return E_FAIL;
		}
		CATIDocRoots* pDocRoots = NULL;
		rc = pSelectedDoc->QueryInterface(IID_CATIDocRoots,
						  (void **) &pDocRoots);
		if (FAILED(rc) || NULL == pSelectedDoc) {
			CAAPstPFSTRACE("Failed to query CATIDocRoots");
			return E_FAIL;
		}
		CATListValCATBaseUnknown_var* pRootProducts = 
			pDocRoots->GiveDocRoots();
		if (NULL == pRootProducts || pRootProducts->Size() <= 0) {
			CAAPstPFSTRACE("Failed to get root products");
			return E_FAIL;
		}
		if (NULL != pDocRoots) {
			pDocRoots->Release();
			pDocRoots = NULL;
		}
		CATIProduct_var spRootProduct = (*pRootProducts)[1];
		delete pRootProducts;
		pRootProducts = NULL;
		if (NULL_var == spRootProduct) {
			CAAPstPFSTRACE("Failed to retrieve root product");
			return E_FAIL;
		}
		CATIProduct *pProductOnRoot = NULL;
		rc = spRootProduct->QueryInterface(IID_CATIProduct,
						   (void **) &pProductOnRoot);
		if (FAILED(rc) || NULL == pProductOnRoot) {
			CAAPstPFSTRACE("Failed to query CATIProduct on root product");
			return E_FAIL;
		}
		CATListValCATBaseUnknown_var* childrenList =
			pProductOnRoot->GetAllChildren();
		if (NULL == childrenList || childrenList->Size() < 2) {
			CAAPstPFSTRACE("Failed to get children of root product");
			return E_FAIL;
		}
		CATIProduct_var spProductToAdd = (*childrenList)[2];
		oList->Append(spProductToAdd);

		pProductOnRoot->Release();
		pProductOnRoot = NULL;
		delete childrenList;
		childrenList = NULL;
	}

	CAAPstPFSTRACE("Exiting CAAPstProductFileSelection::ExtractProducts");
	return S_OK;
}
