# COPYRIGHT DASSAULT SYSTEMES 2002
#======================================================================
# Imakefile for module CAAPeoRunUserAlgorithm.m
#======================================================================
#
#  Jul 2002  Creation: Code generated by the CAA wizard  SOC
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)  OptimizationItf \
									CATObjectModelerBase CATObjectSpecsModeler \
									JS0GROUP JS0FM JS0SCBAK Collections\
									KnowledgeItf\
									CAAPeoBasis \
									CAAPeoCreateUserAlgorithm

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
