# COPYRIGHT DASSAULT SYSTEMES 2006
#======================================================================
# Imakefile for module CAAE5iUEDocumentName.m
#======================================================================
#
#  Jan 2006  Creation: Code generated by the CAA wizard  DRT
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP JS0FM JS0CORBA JS0STDLIB AS0STARTUP \
                      CATPDMBaseItfCPP AD0XXBAS
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
