# COPYRIGHT DASSAULT SYSTEMES 2000
#======================================================================
# Imakefile for module CAAAuiCreateCstOnParts.m 
#======================================================================
#
#  Mar 2000  Creation: Code generated by the CAA wizard  LLE
#======================================================================
#
# LOAD MODULE
#

#ifdef CATIAV5R5
BUILT_OBJECT_TYPE=LOAD MODULE

LINK_WITH = CATObjectSpecsModeler \
            CATObjectModelerBase \
            CATProductStructure1 \
            CATMecModInterfaces \
            KnowledgeItf \
            CATConstraintModelerItf \
            CATAssemblyInterfaces\
            NS0SI18N


LOCAL_CCFLAGS=  -DSPECDEBUG
#endif





