// COPYRIGHT DASSAULT SYSTEMES 2002

// Local framework
#include "CAAXMLSAXCountDocHandler.h"

// System framework
#include "CATUnicodeString.h"     // For NLS string operations

// XMLParser framework
#include "CATISAXAttributeList.h" // To get attributes generated by the StartElement event

// Standard C++ library
#include <iostream.h>

// Declare the class as a V5 component derived from CATSAXHandlerBase
CATImplementClass( CAAXMLSAXCountDocHandler, Implementation, CATSAXHandlerBase, CATnull );

// Implement the CATISAXDocumentHandler interface
#include "TIE_CATISAXDocumentHandler.h"
TIE_CATISAXDocumentHandler(CAAXMLSAXCountDocHandler);


CAAXMLSAXCountDocHandler::CAAXMLSAXCountDocHandler() {
	// Reset the XML constructs counters
	_characterCount = 0;
	_spaceCount = 0;
	_eltsCount = 0;
	_attrCount = 0;
	_piCount = 0;
}

CAAXMLSAXCountDocHandler::~CAAXMLSAXCountDocHandler() {
}

HRESULT CAAXMLSAXCountDocHandler::Characters(
	const CATUnicodeString & iCharacters) {

	// This event is sent by the CATISAXParser when a XML text is parsed
	_characterCount += iCharacters.GetLengthInChar();
	return S_OK;
}

HRESULT CAAXMLSAXCountDocHandler::EndDocument() {
	// This event is sent by the CATISAXParser when the end of
	// the document has been reached. It is a good place to
	// print the statistics collected so far.

	cout << "Element count = " << _eltsCount << endl;
	cout << "Attribute count = " << _attrCount << endl;
	cout << "Character count = " << _characterCount << endl;
	cout << "Ignorable white space count = " << _spaceCount << endl;
	cout << "Processing instruction count = " << _piCount << endl;
	return S_OK;
}
	
HRESULT CAAXMLSAXCountDocHandler::IgnorableWhiteSpace(
	const CATUnicodeString & iCharacters) {

	// This event is sent by the CATISAXParser when an ignorable XML whitespace is parsed
	_spaceCount += iCharacters.GetLengthInChar();
	return S_OK;
}

HRESULT CAAXMLSAXCountDocHandler::ProcessingInstruction(
	const CATUnicodeString & iTarget,
	const CATUnicodeString & iData) {

	// This event is sent by the CATISAXParser when a new XML processing instruction is parsed
	_piCount++;
	return S_OK;
}

HRESULT CAAXMLSAXCountDocHandler::StartElement(
	const CATUnicodeString & iName, 
	const CATISAXAttributeList_var& iAttributes) {

	// This event is sent by the CATISAXParser when a new XML element is parsed
	_eltsCount++;

	// The attributes of an XML element are provided in
	// the StartElement event in the form of a CATISAXAttributeList
	if (iAttributes != NULL_var) {

		// Count the number of attributes in the list.
		unsigned int length = 0;
		HRESULT hr = iAttributes->GetLength(length);
		if (SUCCEEDED(hr)) {
			_attrCount += length;
		}
	}
	return S_OK;
}
