# COPYRIGHT Dassault Systemes 2008
#======================================================================
# Imakefile for module CAAPstHandleImpactOn.m
#======================================================================
#
#  Apr 2008  Creation: Code generated by the CAA wizard  GRO
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP AC0XXLNK AS0STARTUP CATProductStructureInterfaces CATxPDMInterfaces
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
