// COPYRIGHT Dassault Systemes 2004
//===================================================================
//
// CAAIGSMSewSkinBasic.h
// Define the CAAIGSMSewSkinBasic interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Dec 2004  Creation: Code generated by the CAA wizard  pey
//===================================================================
#ifndef CAAIGSMSewSkinBasic_H
#define CAAIGSMSewSkinBasic_H

#include "CAAGsiFeaturesSplModel.h"
#include "CATGSMOrientation.h"
#include "CATBaseUnknown.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByCAAGsiFeaturesSplModel IID IID_CAAIGSMSewSkinBasic;
#else
extern "C" const IID IID_CAAIGSMSewSkinBasic ;
#endif

//------------------------------------------------------------------

/**
 * Describe the functionality of your interface here
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 */
class CATISpecObject_var ; 

class ExportedByCAAGsiFeaturesSplModel CAAIGSMSewSkinBasic: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

    
     
    
    /**
    * Sets/Gets SurfaceToSew . 
    */
    virtual HRESULT SetSurfaceToSew ( CATISpecObject_var ispSurfaceToSew ) = 0 ;
    virtual HRESULT   GetSurfaceToSew ( CATISpecObject_var & ospSurfaceToSew) = 0 ;
    
    /**
    * Sets/Gets  SurfaceSupport. 
    */
    virtual HRESULT SetSurfaceSupport ( CATISpecObject_var  ispSupport ) = 0 ;
    virtual HRESULT GetSurfaceSupport ( CATISpecObject_var  & ospSupport) = 0 ;
    
    /**
    * Sets/Gets  the orientation used to compute the split. 
    */
    virtual HRESULT SetOrientation(CATGSMOrientation iOrientation) = 0;
    virtual HRESULT GetOrientation(CATGSMOrientation & oOrientation) = 0;
    virtual HRESULT InvertOrientation() = 0;
    
   
  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};

//------------------------------------------------------------------

CATDeclareHandler( CAAIGSMSewSkinBasic, CATBaseUnknown );
#endif
