// COPYRIGHT Dassault Systemes 2006
//===================================================================
//
// CAAIGSMCircleSweepTg.h
// Define the CAAIGSMCircleSweepTg interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Dec 2004  Creation: Code generated by the CAA wizard  pey
//===================================================================
#ifndef CAAIGSMCircleSweepTg_H
#define CAAIGSMCircleSweepTg_H

#include "CAAGsiFeaturesSplModel.h"
#include "CATBaseUnknown.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByCAAGsiFeaturesSplModel IID IID_CAAIGSMCircleSweepTg;
#else
extern "C" const IID IID_CAAIGSMCircleSweepTg ;
#endif

//------------------------------------------------------------------

class CATISpecObject_var; 

/**
 * Describe the functionality of your interface here
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 */
class ExportedByCAAGsiFeaturesSplModel CAAIGSMCircleSweepTg: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

   /**
    * Sets / Gets CurveRef 
    */
    virtual HRESULT SetCurveRef ( const CATISpecObject_var ipCurveRef ) = 0 ;
    virtual HRESULT GetCurveRef (  CATISpecObject_var &ipCurveRef ) = 0 ;
    
    /**
    * Sets / Gets Support 
    */
    virtual HRESULT SetSurfaceSupport ( const CATISpecObject_var  ipSupport ) = 0 ;
    virtual HRESULT GetSurfaceSupport (  CATISpecObject_var &ipSupport ) = 0 ;
    
    /**
    * Sets/Gets Trim 
    */
    virtual    HRESULT SetTrimMode(const int iTrimMode) = 0;
    virtual    HRESULT GetTrimMode(int  & oTrimMode) = 0;

    /**
    * Sets/Gets Radius 
    */
    virtual    HRESULT SetRadius(const double iRadius) = 0;
    virtual    HRESULT GetRadius(double  & oRadius) = 0;
    /**
    * Sets/Gets Solution 
    */
    virtual    HRESULT SetSolution(const int iSolution) = 0;
    virtual    HRESULT GetSolution(int  & oSolution) = 0;
    

  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};

//------------------------------------------------------------------
CATDeclareHandler( CAAIGSMCircleSweepTg, CATBaseUnknown );
#endif
