// COPYRIGHT Dassault Systemes 2006
//===================================================================
//
// CAAIGSMFeaturesSplFactory.h
// Define the CAAIGSMFeaturesSplFactory interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Dec 2004  Creation: Code generated by the CAA wizard  pey
//===================================================================
#ifndef CAAIGSMFeaturesSplFactory_H
#define CAAIGSMFeaturesSplFactory_H

#include "CAAGsiFeaturesSplModel.h"
#include "CATBaseUnknown.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByCAAGsiFeaturesSplModel IID IID_CAAIGSMFeaturesSplFactory;
#else
extern "C" const IID IID_CAAIGSMFeaturesSplFactory ;
#endif

//------------------------------------------------------------------

/**
 * Describe the functionality of your interface here
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 */

class CATISpecObject;
class CAAIGSMSewSkinBasic;
class CAAIGSMCircleSweepTg;
class ExportedByCAAGsiFeaturesSplModel CAAIGSMFeaturesSplFactory: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

   
 /**
   * Creates a SewSkin 
   * param ipSurfaceToSew       : the first input Surface
   * param ipSurfaceSupport     : the second  input Surface
   */
   virtual CAAIGSMSewSkinBasic  *  CreateSewSkinBasic (  CATISpecObject *ipSurfaceToSew , CATISpecObject *ipSurfaceSupport ) = 0 ;

    /**
   * Creates a SewSkin 
   * param ipSurfaceToSew       : the first input Surface
   * param ipSurfaceSupport     : the second  input Surface
   */
   virtual CAAIGSMCircleSweepTg *  CreateCircleSweepTg (  CATISpecObject *ipCurveRef  , CATISpecObject *ipSurfaceSupport , double radius ) = 0 ;

  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};

CATDeclareHandler( CAAIGSMFeaturesSplFactory, CATBaseUnknown );
//------------------------------------------------------------------
#endif 
