// COPYRIGHT DASSAULT SYSTEMES 2002
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework CAAOBMInterfaces.edu
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Oct 2002  Creation: Code generated by the CAA wizard  jpi
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("ApplicationFrame",Public);
AddPrereqComponent("Dialog",Public);
AddPrereqComponent("System",Public);
// END WIZARD EDITION ZONE
AddPrereqComponent("CATBehaviorInterfaces",Public);
AddPrereqComponent("CATOBMInterfaces",Public);
AddPrereqComponent("DialogEngine",Public);
AddPrereqComponent("KnowledgeInterfaces",Public);
AddPrereqComponent("ProductStructure",Public);
AddPrereqComponent("ObjectModelerBase",Public);
AddPrereqComponent("ObjectSpecsModeler",Public);

AttachComponent("CAAOBMInterfaces.tst");

