// COPYRIGHT Dassault Systemes 2000
//========================================================================
//
// CAAIBiogNovel.h
// 
//
//========================================================================
//  Dec 2000  Creation: Code generated by the CAA wizard  ADI
//===================================================================
#ifndef CAAIBiogNovel_H
#define CAAIBiogNovel_H

#include "CAAOsmManageExtensions.h"
#include "CATBaseUnknown.h"
#include "CATUnicodeString.h"

extern ExportedByCAAOsmManageExtensions IID IID_CAAIBiogNovel ;

//------------------------------------------------------------------

/**
 * This interface sets and retrieves the values of "Epoch" and "Domain".
 * It is intended to be implemented on the CAAOsmBiographicalNovel
 * extension late type.
 */
class ExportedByCAAOsmManageExtensions CAAIBiogNovel: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

    /**
     * Retrieves the value of the "Epoch" attribute of the CAAOsmBiographicalNovel
	 * extension.     
     *   @param oEpoch
     *      The current value of the "Epoch" attribute.
     */
    virtual HRESULT GetEpoch (CATUnicodeString *oEpoch) const = 0;


   /**
     * Sets the value of the "Epoch" attribute of the CAAOsmBiographicalNovel
	 * extension.     
     *   @param iEpoch
     *      The new value of the "Epoch" attribute.
     */
	virtual HRESULT SetEpoch (const CATUnicodeString iEpoch) = 0;

	/**
     * Retrieves the value of the "Domain" attribute of the CAAOsmBioggraphicalNovel
	 * extension.     
     *   @param oDomain
     *      The current value of the "Domain" attribute.
     */
	virtual HRESULT GetDomain (CATUnicodeString *oDomain) const = 0;

	/**
     * Sets the value of the "Domain" attribute of the CAAOsmBioggraphicalNovel
	 * extension.     
     *   @param iDomain
     *      The new value of the "Domain" attribute.
     */
	virtual HRESULT SetDomain (const CATUnicodeString iDomain) = 0;

};

//------------------------------------------------------------------

#endif
