/**
* @fullreview  KUI RCI 07:03:12
* @quickreview KUI 07:04:12 IR 579844
*/
// COPYRIGHT Dassault Systemes 2007
//===================================================================
//
// CATPDMAllowLoad.cpp
// Provide implementation to interface
//    CATIPDMUEAllowDocumentLoading
//
//===================================================================
//
// Usage notes: Implementation of CATIPDMUEAllowDocumentLoading.
//
//===================================================================
//  Jan 2007  Creation: Code generated by the CAA wizard  KUI
//===================================================================

//===================================================================
//  NOTE for this Sample Implementation:
//===================================================================
//In order to use the interface implementation has to be provided as 
//what is provided in this CPP file.
//
//In addition dictionary entries have to be made in the ".dic" file 
//of the framework in which the implemention module is placed.
//
//The order of the entries is as follows:
//Late-Type  Interface_name  library(dll)_name.
//for eg. for this implementation the dictionary entries would be
// VPM1_AllowDocLoad             CATIPDMUEAllowDocumentLoading                 libCATPDMAllowDocLoad
//
//The size of the documents supplied to the interface is in MBs.
//====================================================================

//PES Highlight
#include "CAACATPDMAllowLoad.h"
#include "CATIPDMUEAllowDocumentLoading.h"
#include <iostream.h>

//System
#include "CATUnicodeString.h"

// Tie the implementation to its interface
// ---------------------------------------
#include "TIE_CATIPDMUEAllowDocumentLoading.h"
TIEchain_CATIPDMUEAllowDocumentLoading( CAACATPDMAllowLoad );

CATImplementClass( CAACATPDMAllowLoad,
                   DataExtension,
                   CATBaseUnknown,
		   VPM1_AllowDocLoad
                   );
                   
//-----------------------------------------------------------------------------
//  CAACATPDMAllowLoad: constructor
//-----------------------------------------------------------------------------
CAACATPDMAllowLoad::CAACATPDMAllowLoad():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// CAACATPDMAllowLoad: destructor
//-----------------------------------------------------------------------------
CAACATPDMAllowLoad::~CAACATPDMAllowLoad()
{
}   
   
//-----------------------------------------------------------------------------
// CAACATPDMAllowLoad: AllowDocumentLoading
//-----------------------------------------------------------------------------
HRESULT CAACATPDMAllowLoad::AllowDocumentLoading(int iNbDocs, CATIDocId **iListDocIds, double **ipDocSize)
{
  CATUnicodeString strTemp;  //temp string to obtain docid_identifier.

  
  for(int count=1 ; count<=iNbDocs ; count++)
  {
    if (iListDocIds && iListDocIds[count-1])
      iListDocIds[count-1]->GetIdentifier(strTemp);  //Retrieving identifiers and printing.
    strTemp.BuildFromNum(*ipDocSize[count-1] ,"%g"); 
    cout<<"Docid ="<< iListDocIds[count-1]<<endl;
    cout<<"Size  ="<<*ipDocSize[count-1]<<endl;
  }

  //Size Check implementation.
  //Here the customer will have to implement his logic to check if the 
  //free memory if enough to load the docs being loaded as per their size
  //Sample implementation below
  double d_Size = 0.0; //temp double to store cumulative size.

  for(count =1 ; count<=iNbDocs ; count++)
    {
      d_Size = d_Size + *ipDocSize[count-1]; //Retrieving and adding up the size of the documents for load.
    }

  if(d_Size < 200.0)                // If the size is less than 200MB allow document loading else stop document from loading.
      return S_OK;
  else
    return E_FAIL;
}      
//-----------------------------------------------------------------------------
