// COPYRIGHT Dassault Systemes 2005
//===================================================================
//
// CAAOBMInterfacesDlg.cpp
// The dialog : CAAOBMInterfacesDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  May 2005  Creation: Code generated by the CAA wizard  auw
//===================================================================
#include "CAAOBMInterfacesDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#include "CATIVariableManagement.h"
#include "CATIValue.h"
#include "CATITypeDictionary.h"
#include "CATIType.h"
#include "CATICkeParm.h"
#include "CATICkeParmFactory.h"
#include "CATCkeGlobalFunctions.h"
#include "CATFrmEditor.h"
#include "CATIProduct.h"
#include "CATIPrdObjectPublisher.h"
#include "CATIDocRoots.h"
#include "CATDocument.h"
#include "CATIConnector.h"
#include "CATILinkableObject.h"

//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
CAAOBMInterfacesDlg::CAAOBMInterfacesDlg(CATBaseUnknown *iBehavior) :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"CAAOBMInterfacesDlg",CATDlgWndBtnOKCancel|CATDlgWndTitleBarHelp|CATDlgGridLayout

//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{

	_Frame003 = NULL;
	_Label004 = NULL;
	_EditorValueOfParm = NULL;
	_ApplySetValue = NULL;
	_Label007 = NULL;
	_Label008 = NULL;
	_Label009 = NULL;
	_PushButtonSetLink = NULL;
	_PublicationName = NULL;
	_PushButton012 = NULL;
	_ComboParmType = NULL;

	_Behavior = iBehavior;
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
CAAOBMInterfacesDlg::~CAAOBMInterfacesDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _Frame003 = NULL;
 _Label004 = NULL;
 _EditorValueOfParm = NULL;
 _ApplySetValue = NULL;
 _Label007 = NULL;
 _Label008 = NULL;
 _Label009 = NULL;
 _PushButtonSetLink = NULL;
 _PublicationName = NULL;
 _PushButton012 = NULL;
 _ComboParmType = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _Behavior = NULL;
}

void CAAOBMInterfacesDlg::Build()
{
	//  TODO: This call builds your dialog from the layout declaration file
	//  -------------------------------------------------------------------

	//CAA2 WIZARD WIDGET CONSTRUCTION SECTION

	_Frame003 = new CATDlgFrame(this, "Frame003", CATDlgGridLayout);
	_Frame003 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);


	_Label004 = new CATDlgLabel(_Frame003, "Label004");
	_Label004 -> SetGridConstraints(0, 0, 1, 1, CATGRID_RIGHT);
	_EditorValueOfParm = new CATDlgEditor(_Frame003, "Editor005");
	_EditorValueOfParm -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
	_ApplySetValue = new CATDlgPushButton(_Frame003, "PushButton006");
	_ApplySetValue -> SetGridConstraints(0, 2, 1, 1, CATGRID_RIGHT);

	CATDlgLabel *Labelvide1 = new CATDlgLabel(_Frame003, "LabelVide1");
	Labelvide1 -> SetGridConstraints(1, 0, 1, 1, CATGRID_RIGHT);
	Labelvide1->SetTitle(" ");

	_Label007 = new CATDlgLabel(_Frame003, "Label007");
	_Label007 -> SetGridConstraints(2, 0, 1, 1, CATGRID_RIGHT);
	_PushButtonSetLink = new CATDlgPushButton(_Frame003, "PushButton010");
	_PushButtonSetLink -> SetGridConstraints(2, 2, 1, 1, CATGRID_RIGHT);

	CATDlgLabel *Labelvide2 = new CATDlgLabel(_Frame003, "LabelVide2");
	Labelvide1 -> SetGridConstraints(1, 0, 1, 1, CATGRID_RIGHT);
	Labelvide2->SetTitle(" ");

	_Label008 = new CATDlgLabel(_Frame003, "Label008");
	_Label008 -> SetGridConstraints(4, 0, 1, 1, CATGRID_RIGHT);
	_ComboParmType = new CATDlgCombo(_Frame003, "Combo013", CATDlgCmbDropDown);
	_ComboParmType -> SetGridConstraints(4, 1, 1, 1, CATGRID_4SIDES);

	CATDlgLabel *Labelvide3 = new CATDlgLabel(_Frame003, "LabelVide3");
	Labelvide3 -> SetGridConstraints(5, 0, 1, 1, CATGRID_4SIDES);
	Labelvide3->SetTitle(" ");

	_Label009 = new CATDlgLabel(_Frame003, "Label009");
	_Label009 -> SetGridConstraints(6, 0, 1, 1, CATGRID_RIGHT);
	_PublicationName = new CATDlgEditor(_Frame003, "Editor011");
	_PublicationName -> SetGridConstraints(6, 1, 1, 1, CATGRID_4SIDES);
	_PushButton012 = new CATDlgPushButton(_Frame003, "PushButton012");
	_PushButton012 -> SetGridConstraints(6, 2, 1, 1, CATGRID_RIGHT);

	//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

	//CAA2 WIZARD CALLBACK DECLARATION SECTION
	AddAnalyseNotificationCB (_ApplySetValue, _ApplySetValue->GetPushBActivateNotification(),
		(CATCommandMethod)&CAAOBMInterfacesDlg::OnPushButtonChangeAttValue,NULL);

	AddAnalyseNotificationCB (_PushButtonSetLink, _PushButtonSetLink->GetPushBActivateNotification(),
		(CATCommandMethod)&CAAOBMInterfacesDlg::OnPushButtonSetLink,NULL);

	AddAnalyseNotificationCB (_ComboParmType, _ComboParmType->GetComboSelectNotification(),
		(CATCommandMethod)&CAAOBMInterfacesDlg::OnChangeAttType,NULL);

	AddAnalyseNotificationCB (_PushButton012, _PushButton012->GetPushBActivateNotification(),
		(CATCommandMethod)&CAAOBMInterfacesDlg::OnPushButtonValueAttWithPub,NULL);

	//END CAA2 WIZARD CALLBACK DECLARATION SECTION


	//We initialize the editor with the value of "Beh_Out2" variable
	CATIValue *piValue = NULL;
	CATUnicodeString VarName = "Beh_Out2";
	//We get the CATIVariableManagement interface on the behavior, which is passed as an argument in the dialog constructor
	CATIVariableManagement_var hBehVarMngt = _Behavior;
	HRESULT hr = hBehVarMngt->GetVariableValue(&VarName,tio_OUT,&piValue);

	if(SUCCEEDED(hr) && piValue)
	{
		CATUnicodeString EdtValue;
		if (SUCCEEDED(piValue->AsString(EdtValue)))
			_EditorValueOfParm->SetText(EdtValue);
		piValue->Release();
		piValue = NULL;
	}

	//We will only consider those 3 knowledge types in this example.
	_ComboParmType->SetLine("ObjectType");
	_ComboParmType->SetLine("Part");
	_ComboParmType->SetLine("Product");

	//We retrieve the knowledge Dictonary and the searched CATIType
	CATIType* piPointedVarType = NULL;
	CATIType* piVarType = NULL;
	VarName = "P1";
	//We set the value of the "P1" IN variable of the behavior
	HRESULT HR = hBehVarMngt->GetVariableType(&VarName,tio_IN,&piVarType, &piPointedVarType);
	CATUnicodeString PubType;
	if(SUCCEEDED(HR) && piPointedVarType && piVarType)
	{
		PubType = piPointedVarType->Name();
		_ComboParmType->SetSelect(PubType);
		
		piPointedVarType->Release();
		piPointedVarType = NULL;
		
		piVarType->Release();
		piVarType = NULL;
	}
}

void CAAOBMInterfacesDlg::OnPushButtonChangeAttValue(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
	CATUnicodeString EdtValue = _EditorValueOfParm->GetText();

	//We have to build the CATIValue object corresponding to the user entry
	CATICkeParm_var hValueParmReal;
	CATICkeParmFactory_var CkeParmFactory=CATCkeGlobalFunctions::GetVolatileFactory();

	if(NULL_var!=CkeParmFactory)
		hValueParmReal =CkeParmFactory->CreateString("StringOnBeh",EdtValue);
	
	CATIValue* piValueParm = NULL;
	HRESULT rc = E_FAIL;

	if(NULL_var!=hValueParmReal)
		rc =  hValueParmReal->QueryInterface(IID_CATIValue, (void**) &piValueParm);

	if(SUCCEEDED(rc))
	{
		//We can now retrieve the CATIVariableManagement interface on the behavior and set the value of "Beh_Out2" variable
		CATIVariableManagement_var hVarMngt = _Behavior;
		CATUnicodeString VarName = "Beh_Out2";
		if(!!hVarMngt)
			hVarMngt->SetVariableValue(&VarName,tio_OUT,piValueParm);

		piValueParm->Release();
		piValueParm = NULL;
	}

}
void CAAOBMInterfacesDlg::OnPushButtonSetLink(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{

	//We want to retrieve the CATIVariableManagement interface on the typed Root Product
	//As it is typed with an extended object, it will adhere to CATIVariableManagement.
	//We will then be able to manipulate its variables
	
	
	//We retrieve the root product
	//---------------------------
	CATFrmEditor * editor = CATFrmEditor::GetCurrentEditor();
	CATDocument * pDoc =NULL;
	if (editor)
		pDoc = editor->GetDocument();

	CATIDocRoots *piDocRootsOnDoc = NULL;
	if(!pDoc)
		return;
	HRESULT rc = pDoc -> QueryInterface(IID_CATIDocRoots,(void**)&piDocRootsOnDoc);
	if ( FAILED(rc) || !piDocRootsOnDoc ) return;

	// get the root product which is the first element of the list returned by GiveDocRoots
	CATListValCATBaseUnknown_var* pRootProducts = piDocRootsOnDoc -> GiveDocRoots();
	CATIProduct_var root_product;
	if (pRootProducts && pRootProducts->Size())
	{
		root_product = (*pRootProducts)[1];
		delete pRootProducts;
		pRootProducts = NULL;
	}
	piDocRootsOnDoc->Release();
	piDocRootsOnDoc = NULL;
	// End of root product search
	//---------------------------

	//we get the CATIVariableManagement interface on the extended root product
	CATIVariableManagement_var hProdVarMngt = root_product;
	CATIVariableManagement_var hBehVarMngt = _Behavior;
	if(!!hProdVarMngt && !!hBehVarMngt)
	{
		CATBaseUnknown* pAttOnType = NULL;
		CATUnicodeString VarNameType = "AttonType";
		//We retrieve the "AttonType" variable on the extended product
		HRESULT hr = hProdVarMngt->GetVariable(&VarNameType, tio_IN,&pAttOnType);
		if(SUCCEEDED(hr) && pAttOnType)
		{
			CATUnicodeString VarNameBeh = "Beh_In1";
			//we can now link the "Beh_In1" variable, defined on the Command behavior, with 
			//"AttonType" retrieved on the extended object
			hr = hBehVarMngt->LinkVariables(&VarNameBeh,tio_IN,pAttOnType);
			if( SUCCEEDED(hr))
			{
				CATDlgNotify* warning = new CATDlgNotify (CATApplicationFrame::GetFrame()->GetMainWindow(), "Link",  CATDlgNfyInformation);
				CATUnicodeString message = CATMsgCatalog::BuildMessage("CAAOBMInterfacesDlg","LINK_DONE");
				CATUnicodeString title = CATMsgCatalog::BuildMessage("CAAOBMInterfacesDlg","INFORMATION");
				warning->DisplayBlocked(message, title);
				warning->RequestDelayedDestruction();
			}

			pAttOnType->Release();
			pAttOnType = NULL;
		}
	}
}

void CAAOBMInterfacesDlg::OnChangeAttType(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
	CATUnicodeString SelectedType ;
	_ComboParmType->GetLine(SelectedType,_ComboParmType->GetSelect());
	
	//First, we have to retrieved the CATIType corresponding to the combo selection
	CATIType_var TheType;
	CATITypeDictionary_var dico = CATGlobalFunctions::GetTypeDictionary();
	if( !!dico)
	{	
		HRESULT rc = dico->FindType(SelectedType, TheType);
		CATIVariableManagement_var hBehVarMngt = _Behavior;
		if( SUCCEEDED(rc) &&  !!hBehVarMngt && !!TheType)
		{
			CATUnicodeString VarName = "P1";
			//we're now able to change the type of "P1" variable
			HRESULT HR = hBehVarMngt->SetVariableType(&VarName,tio_IN,TheType);
		}
	}
}

void CAAOBMInterfacesDlg::OnPushButtonValueAttWithPub(CATCommand* cmd, CATNotification* evt, CATCommandClientData data)
{
	CATUnicodeString PubName = _PublicationName->GetText();
	
	//We have to retrieve the publication corresponding to user input
	//------------------
	CATFrmEditor * editor = CATFrmEditor::GetCurrentEditor();
	CATDocument * pDoc =NULL;
	if (editor)
		pDoc = editor->GetDocument();
	if(!pDoc)
		return;
	CATIDocRoots *piDocRootsOnDoc = NULL;
	HRESULT rc = pDoc -> QueryInterface(IID_CATIDocRoots,(void**)&piDocRootsOnDoc);
	if ( FAILED(rc) ) return;

	// get the root product which is the first element of the list returned by GiveDocRoots
	CATListValCATBaseUnknown_var* pRootProducts = piDocRootsOnDoc -> GiveDocRoots();
	CATIProduct_var root_product;
	if (pRootProducts && pRootProducts->Size())
	{
		root_product = (*pRootProducts)[1];
		delete pRootProducts;
		pRootProducts = NULL;
	}
	piDocRootsOnDoc->Release();
	piDocRootsOnDoc = NULL;
	
	CATIPrdObjectPublisher_var RootPrd_Publications=root_product;

	if(!!RootPrd_Publications)
	{
		CATBaseUnknown* RetrievedPub = NULL;
		CATUnicodeString RetrievedObj_Name;
		RetrievedPub = RootPrd_Publications->GetFinalObject(PubName);
		//The searched publication does not exists, we send an error panel
		if(!RetrievedPub)
		{
			CATDlgNotify* warning = new CATDlgNotify (CATApplicationFrame::GetFrame()->GetMainWindow(), "Bad_Publi",  CATDlgNfyWarning);
			CATUnicodeString message = CATMsgCatalog::BuildMessage("CAAOBMInterfacesDlg","BAD_PUB",&PubName,1);
			CATUnicodeString title = CATMsgCatalog::BuildMessage("CAAOBMInterfacesDlg","WARNING");
			warning->DisplayBlocked(message, title);
			warning->RequestDelayedDestruction();
			return;
		}
		//End of publication search
		///---------------------
		
		else
		{
			//the publication exists, we can now retrieve the published object

			CATIConnector_var Connector = RetrievedPub;
			CATILinkableObject_var LinkObj;
			if(NULL_var!=Connector)
				LinkObj = Connector->GiveReferenceObject();

			//The publication is retrieved, we will valuate "P1" attribute of the Command behavior with it
			CATICkeParmFactory_var CkeParmFactory=CATCkeGlobalFunctions::GetVolatileFactory();
			if(!!CkeParmFactory)
			{
				CATICkeParm_var PubRef = CkeParmFactory->CreateObjectReference(LinkObj);
				if(!!PubRef)
				{
					CATIValue * ValuePub = NULL;
					HRESULT rc = PubRef->QueryInterface(IID_CATIValue, (void**)&ValuePub);
					CATIVariableManagement_var hVarMngt = _Behavior;
					if(SUCCEEDED(rc) && !!hVarMngt)
					{
						CATUnicodeString VarName = "P1";
						rc = hVarMngt->SetVariableValue(&VarName, tio_IN,ValuePub);
						ValuePub->Release();
						ValuePub = NULL;
						if(FAILED(rc))
						{
							CATDlgNotify* warning = new CATDlgNotify (CATApplicationFrame::GetFrame()->GetMainWindow(), "Wrong_Type",  CATDlgNfyWarning);
							CATUnicodeString message = CATMsgCatalog::BuildMessage("CAAOBMInterfacesDlg","WRONG_TYPE",&VarName,1);
							CATUnicodeString title = CATMsgCatalog::BuildMessage("CAAOBMInterfacesDlg","WARNING");
							warning->DisplayBlocked(message, title);
							warning->RequestDelayedDestruction();
						}
					}
				}
			}
			RetrievedPub->Release();
			RetrievedPub = NULL;
		}
	}

}



