// COPYRIGHT Dassault Systemes 2005
//===================================================================
//
// CAAOBMInterfacesCommand.cpp
// The state chart based command: CAAOBMInterfacesCommand
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  May 2005  Creation: Code generated by the CAA wizard  auw
//===================================================================
#include "CAAOBMInterfacesCommand.h"
#include "CATIVariableManagement.h"
#include "CATIBehOperationManagement.h"
#include "CATCreateExternalObject.h"

CATCreateClassArg( CAAOBMInterfacesCommand, CATBaseUnknown);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
CAAOBMInterfacesCommand::CAAOBMInterfacesCommand(CATBaseUnknown *iBehavior) :
CATStateCommand ("CAAOBMInterfacesCommand", CATCommandMsgRequestSharedMode)
,_Behavior(NULL)
{
	_Behavior = iBehavior;
	if(_Behavior)
		_Behavior->AddRef();
	//The command starts.
	//We inform the Behaviors engine through the CATIBehOperationManagement::Start method
	CATIBehOperationManagement_var Manage = _Behavior;
	
	if( !!Manage)
		Manage->Start();

	_CAAOBMInterfacesDlg = NULL;
	_OK = NULL;
	_Cancel = NULL;

	if( !!Manage)
		Manage->Suspend();
}

//-------------------------------------------------------------------------
// Default Constructor
//-------------------------------------------------------------------------
CAAOBMInterfacesCommand::CAAOBMInterfacesCommand() :  CATStateCommand ( "CAAOBMInterfacesCommand", CATCommandMsgRequestSharedMode )
{
//Never used when coding a BKT dedicated command
	_OK = NULL;
	_Cancel = NULL;
	_Behavior = NULL;
	_CAAOBMInterfacesDlg = NULL;
	_Behavior= NULL;
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
CAAOBMInterfacesCommand::~CAAOBMInterfacesCommand()
{
	//Never call any CATIBehOperationManagement method in the destructor.
	//Only delete your variables here
	if(_OK)
	{
		_OK->RequestDelayedDestruction();
		_OK = NULL;
	}

	if(_Cancel)
	{
		_Cancel->RequestDelayedDestruction();
		_Cancel = NULL;
	}

	_CAAOBMInterfacesDlg = NULL;
	if(_Behavior)
	{
		_Behavior->Release();
		_Behavior=NULL;
	}
}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void CAAOBMInterfacesCommand::BuildGraph()
{
	CATIBehOperationManagement_var Manage = _Behavior;
	//The command starts: we inform the behavior by calling Start()
	if( !!Manage)
		Manage->Start();

	if ( ! _CAAOBMInterfacesDlg)
	{
		_CAAOBMInterfacesDlg = new CAAOBMInterfacesDlg(_Behavior);
		_CAAOBMInterfacesDlg->Build();
		_CAAOBMInterfacesDlg->SetVisibility(CATDlgShow);
	}

	// TODO: Define the StateChart 
	// ---------------------------

	CATDialogState * initialState = GetInitialState("initialState");

	_OK			= new CATDialogAgent();  
	_Cancel		= new CATDialogAgent();

	_OK				->AcceptOnNotify		(_CAAOBMInterfacesDlg,_CAAOBMInterfacesDlg->GetDiaOKNotification());
	_Cancel			->AcceptOnNotify (_CAAOBMInterfacesDlg,_CAAOBMInterfacesDlg->GetDiaCANCELNotification());

	// --- Associating Dialog Agents to State ----------------------------------
	initialState->AddDialogAgent(_OK);
	initialState->AddDialogAgent(_Cancel);

	AddTransition( initialState, NULL, IsOutputSetCondition(_OK), NULL);
	AddTransition( initialState, NULL, IsOutputSetCondition(_Cancel), NULL);


	if( !!Manage)
		Manage->Suspend();

}

CATStatusChangeRC CAAOBMInterfacesCommand::Desactivate( CATCommand * iFromClient, CATNotification * iEvtDat)
{
	CATIBehOperationManagement_var Manage = _Behavior;
	//if the command is deactivated, the behavior is deactivated too: we need to call the ::Suspend() method
	if( !!Manage)
	{
		Manage->Start();

		//you can here add some code that you want to execute in the Desactivate method.
		//this code has to be between a call to Start() and one to Suspend()

		Manage->Suspend();
	}

  return (CATStatusChangeRCCompleted);
}


CATStatusChangeRC CAAOBMInterfacesCommand::Activate( CATCommand * iFromClient, CATNotification * iEvtDat)
{
	CATIBehOperationManagement_var Manage = _Behavior;
	//The command activates: the behavior has to be suspended
	if( !!Manage)
	{
		Manage->Start();
		//you can here add some code that you want to execute in the Desactivate method.
		//this code has to be between a call to Start() and one to Suspend()
		Manage->Suspend();
	}

	return (CATStatusChangeRCCompleted);
}

CATStatusChangeRC CAAOBMInterfacesCommand::Cancel( CATCommand * iFromClient, CATNotification * iEvtDat)
{
	CATIBehOperationManagement_var Manage = _Behavior;
	//the command runs its cancel method: the behavior is deactivated by the Done() or Cancel() method.
	//In case of a well-ran operation, we call DOne(), Cancel() otherwise
	if( !!Manage)
	{
		Manage->Start();

		_CAAOBMInterfacesDlg->SetVisibility(CATDlgHide);

		//we exit the panel by clicking OK
		if(_OK->IsOutputSet())
			Manage->Done();
		//we exit using the cancel button
		if(_Cancel->IsOutputSet())
			Manage->Cancel();
	}
	
	return (CATStatusChangeRCCompleted);
}
