# COPYRIGHT DASSAULT SYSTEMES 2003
#======================================================================
# Imakefile for module CAAPstPrdObjectPublisher.m
#======================================================================
#
#  Aug 2003  Creation: Code generated by the CAA wizard  avm
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 
 
LINK_WITH = CATProductStructure1 \
            CATObjectModelerBase \
            CATObjectSpecsModeler \
            JS0GROUP 

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
