# COPYRIGHT DASSAULT SYSTEMES 2004
#======================================================================
# Imakefile for module CAALifIntegrateKnowledge.m
#======================================================================
#
#  Sep 2004  Creation: Code generated by the CAA wizard  aal
#======================================================================

#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE = SHARED LIBRARY
LINK_WITH = JS0GROUP KnowledgeItf CAALifBasis AC0SPBAS AD0XXBAS

