# COPYRIGHT DASSAULT SYSTEMES 2003
#======================================================================
# Imakefile for module CAAV4iEduTranslV4ToV5.m
#======================================================================
#
#  Dec 2003  Creation: Code generated by the CAA wizard  nbl
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 

LINK_WITH = JS0GROUP CATV4iCpV4ToV5 CATV4iServices AD0XXBAS

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
