/**
* @quickReview CRE 04:12:02
*/
//=============================================================================
//
// COPYRIGHT DASSAULT SYSTEMES  2001
//
// Sample code for : Geometric Modeler
// Mission         : Use of the GeometricOperators framework
//                   Creation of CGM attributes.
//
// Explanations    : Basically, to create a CATCGMAttribute, you must use the
//                   CATCGMAttribute::CreateAttribute static method. 
//                   This method returns a CATCGMAttribute meeting the 
//                   conditions specified in the CreateAttribute arguments. 
//                   But actually the data which describe your attribute are specified
//                   in the form of an attribute implementation. For this use case,
//                   the attribute implementation is defined in the CAAGobAttribute module.
//                   If you intend to develop your own attribute implementation, refer to this
//                   module. This use case as well as CAAGobAttributeRead explain
//                   how to manipulate already implemented attributes.
//        
//                   
// Type            : Batch program
// Inputs          : None
// Outputs         : Return codes (in this case, the file is not saved)
//                   0- OK
//                   1- Null pointer detection
//
// Coding steps    : 1- Geometry factory creation
//                   2- Geometry creation (two Plines intended to be
//                      added attributes to)
//                   3- Creation and use of a CAAGobAttributeManagement attribute
//                      a - find the attribute identifier
//                      b - create the attribute
//                      c - set its value
//                      d - add it to each Pline
//                      e - get the number of references to the attribute
//                      f - release the link to one of the PLine
//                      g - get the new number of references to the attribute 
//                   4- Model writing and closing operations
//
// How to run it   : CAAGobAttributeCreation            // to run without storing the NCGM file
//                   CAAGobAttributeCreation  file.NCGM // to run and store the result in file.NCGM                              
//=============================================================================

#include <fstream.h>

// GeometricObjects
#include "CATCGMContainerMngt.h"      // Management of CGM container
#include "CATCGMAttrId.h"             // CGM attribute identifier
#include "CATGeoFactory.h"            // Geometry factory
#include "CATPLine.h"                 // Creation of CATPline
#include "CATPlane.h"                 // Creation of a plane
#include "CATSurParam.h"              // Parameter of a point on a surface

// Mathematics 
#include "CATMathDirection.h"         // Math direction
#include "CATMathPlane.h"             // Math plane
#include "CATMathPoint.h"             // Math point

#include "CAAGobAttributeManagement.h"   // Class defining the attribute to be manipulated

/** @c++ansi mcf 2004-10-08.12:03:56 [include iostream.h for cout declaration] **/
#include "iostream.h"
// ----------------------------------------------------------------------------
int main(int    iArgc,   // Number of arguments (0) or (1) 
         char** iArgv)   // Path to the *.NCGM document generated by the program
{
	
	int rc=0;
	if(2<iArgc) return (1);
	
	char *pfileName = NULL;
	int  toStore = 0;
	if (2==iArgc) 
	{
		toStore = 1; 
		pfileName = iArgv[1];
	}
	
	//-----------------------------------------------------------------------------
	// 1 - Initialize the factory
	//-----------------------------------------------------------------------------
	
	CATGeoFactory* piGeomFactory = ::CATCreateCGMContainer() ;
	if (NULL==piGeomFactory) return (1);
	
	//-----------------------------------------------------------------------------
	// 2 - Create the geometry 
	//-----------------------------------------------------------------------------
	
	// (a) --- Create a CATMathPlane plane
	//
	CATMathPoint origin1 ( 0,0,0);
	CATMathDirection firstDirection1 ( 1,0,0);
	CATMathDirection secondDirection1 ( 0,1,0);
	CATMathPlane plane1 ( origin1 , firstDirection1 , secondDirection1 );
	
	// (b) --- Create a geometric plane 
	//
	CATPlane * piGeoPlane =NULL;
	piGeoPlane = piGeomFactory->CreatePlane(plane1);
	if (NULL==piGeoPlane ) 
	{
		::CATCloseCGMContainer(piGeomFactory);
		return (1);	
	}
	 
	// (c) --- Create a first PLine on piGeoPlane (geometric plane)
	//
	CATPLine * piPline1 = NULL;
	{
        CATSurParam iStartParam1, iEndParam1;
        piGeoPlane->CreateParam(0,0,iStartParam1);
        piGeoPlane->CreateParam(0,80,iEndParam1);
		piPline1 = piGeomFactory->CreatePLine(iStartParam1,iEndParam1,piGeoPlane);
		if (NULL==piPline1 ) 
		{
			::CATCloseCGMContainer(piGeomFactory);
			return (1);	
		}
	}

	// (d) --- Create a second PLine on piGeoPlane (geometric plane)
	//
    CATPLine * piPline2 = NULL;
	{
		CATSurParam iStartParam2, iEndParam2;
        piGeoPlane->CreateParam(0,50,iStartParam2);
        piGeoPlane->CreateParam(20,80,iEndParam2);
		piPline2 = piGeomFactory->CreatePLine(iStartParam2,iEndParam2,piGeoPlane);
		if (NULL==piPline2 ) 
		{
			::CATCloseCGMContainer(piGeomFactory);
			return (1);	
		}
	}

	//-----------------------------------------------------------------------------
	// 3 - Create and manage a CAAGobAttributeManagement attribute
	//-----------------------------------------------------------------------------
    
	// (a) --- Find the attribute identifier
	//
	const char*  iAttr = "CAAGobAttributeManagement";
	const char*  iDomainName = "CAAGobAT";
	const CATCGMAttrId* pAttrId = CATCGMAttrId::FindAttrId(iAttr,iDomainName) ;

	// (b) --- Create the attribute
	//         You can also use the UAIDPtr macro to specify the attribute identifier
	//         Replace pAttrId with  UAIDPtr(CAAGobAttributeManagement)
	//
	CAAGobAttributeManagement * piAttr1 =(CAAGobAttributeManagement *) CATCGMAttribute::CreateAttribute(pAttrId);
	if (NULL==piAttr1 ) 
	{
		cout << "no CAAGobAttributeManagement attribute created" << endl;
		::CATCloseCGMContainer(piGeomFactory);
		return (1);	
	}

	// (c) --- Set its value to 2 
	//         The SetValue method is defined in the CAAGobAttribute.m module
	//
	piAttr1->SetValue(2);
	  
	// (d) --- Add it to the piPline1 and piPline2 CATPlines
	//
	piPline1->PutAttribute(piAttr1);
	piPline2->PutAttribute(piAttr1);

    // (e) --- Retrieve the number of references
	// 
    cout << "Number of objects pointed to by the attribute: (2 expected)";
	cout << piAttr1->GetNbAttrRef() << endl;

	// (f) --- Release the link between the attribute and piPline2 
	// 
	piPline2->ReleaseAttribute(piAttr1);

    // (g) --- Retrieve the new number of references
	// 
	cout << "---------------------------------- " << endl;
	cout << "After ReleaseAttribute on piPline2 " << endl;
	cout << "Number of objects pointed to by the attribute: (1 expected)";
	cout << piAttr1->GetNbAttrRef() << endl;

	//-----------------------------------------------------------------------------
	// 4- Writes the model and close the CGM container
	//-----------------------------------------------------------------------------
	if(1==toStore)
	{
#ifdef _WINDOWS_SOURCE
		ofstream filetowrite(pfileName, ios::binary ) ;
#else
		ofstream filetowrite(pfileName,ios::out,filebuf::openprot) ;
#endif
		
		::CATSaveCGMContainer(piGeomFactory,filetowrite);
		filetowrite.close();
	}	
	
	::CATCloseCGMContainer(piGeomFactory);
	
	return rc;
}


