# COPYRIGHT DASSAULT SYSTEMES 2005
#======================================================================
# Imakefile for module CAAEhiFLEXComputeBundleSegment.m
#======================================================================
#
#  Apr 2005  Creation: Code generated by the CAA wizard  axc
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 


LINK_WITH = JS0GROUP                \ 
		    CATProductStructure1    \
	     	CATLiteralFeatures      \
            CATObjectModelerBase    \
            CATObjectSpecsModeler   \
            CATGitInterfaces        \
            CATEhiInterfaces        \
            CATElectricalInterfaces \
			KnowledgeItf            \
			CATMecModInterfaces

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
