// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CAAPuiPRDWorkshopConfigCmd.cpp
// The command: CAAPuiPRDWorkshopConfigCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Sep 2003  Creation: Code generated by the CAA wizard  avm
//===================================================================
//Application Frame
#include "CATApplicationFrame.h"
#include "CATCmdAccess.h"
#include "CATCmdWorkshop.h"

//Dialog
#include "CATDlgNotify.h"
#include "CATDlgWindow.h"

#include "CAAPuiPRDWorkshopConfigCmd.h"
#include "CAAPuiPRDWorkshopConfigTrace.h"

#include "CATCreateExternalObject.h"
CATCreateClass( CAAPuiPRDWorkshopConfigCmd);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
CAAPuiPRDWorkshopConfigCmd::CAAPuiPRDWorkshopConfigCmd() :
	CATCommand(NULL, "CAAPuiPRDWorkshopConfigCmd")
{
	RequestStatusChange (CATCommandMsgRequestExclusiveMode);
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
CAAPuiPRDWorkshopConfigCmd::~CAAPuiPRDWorkshopConfigCmd()
{
}


//
// Activates a command.
//   iFromClient :The command that requests to activate the current one.
//   iEvtDat :The notification sent.
// ----------------------------------------------------
CATStatusChangeRC CAAPuiPRDWorkshopConfigCmd::Activate(CATCommand *iFromClient,
						       CATNotification *iEvtDat)
{
	CAAPuiPRDWorkshopConfigTRACE (">> CAAPuiPRDWorkshopConfigCmd:Activate()");
	CATApplicationFrame *pApplication = CATApplicationFrame::GetFrame(); 
	if (NULL != pApplication) { 		
 		CATDlgWindow * pMainWindow = pApplication->GetMainWindow();
		CATDlgNotify *pNotifyDlg = new CATDlgNotify
			(pMainWindow, "CAAPuiPRDWorkshopConfig", CATDlgNfyOK);
		if (NULL != pNotifyDlg) {
			pNotifyDlg->DisplayBlocked
				("Hello World!",
				 "CAAPuiPRDWorkshopConfig UseCase");
			pNotifyDlg->RequestDelayedDestruction(); 
		}
	}
	RequestDelayedDestruction();
 
	return (CATStatusChangeRCCompleted);
}
