// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CAAPuiPRDWorkshopConfig.cpp
// Provide implementation to interface CATIPRDWorkshopConfiguration
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Sep 2003  Creation: Code generated by the CAA wizard  avm
//===================================================================
#include "CAAPuiPRDWorkshopConfig.h"
#include "CAAPuiPRDWorkshopConfigTrace.h"
#include "TIE_CATIPRDWorkshopConfiguration.h"
#include "TIE_CAAIPuiPRDWorkshopConfigFactory.h"

// Application Frame
#include "CATCreateWorkshop.h"
#include "CATCommandHeader.h"			// for the MacDeclareHeader macro
#include "CATWorkshopConfigurationFactory.h"	// for the CATDeclareConfigurationFactory macro

 
// ProductStructure
#include "CATIPRDWorkshopConfiguration.h"

CATImplementClass(CAAPuiPRDWorkshopConfig,
		  Implementation,
		  CATBaseUnknown,
		  CATnull);
 
// Tie the implementation to its interface
// ---------------------------------------
TIE_CATIPRDWorkshopConfiguration(CAAPuiPRDWorkshopConfig);


// Create our command header class
MacDeclareHeader(CAAPuiPRDWorkshopConfigHeader);

// Create our factory class
CATDeclareConfigurationFactory(CAAPuiPRDWorkshopConfig);
CATImplementConfigurationFactory(CAAPuiPRDWorkshopConfig,
				 CAAIPuiPRDWorkshopConfigFactory);

//-----------------------------------------------------------------------------
// CAAPuiPRDWorkshopConfig : constructor
//-----------------------------------------------------------------------------
CAAPuiPRDWorkshopConfig::CAAPuiPRDWorkshopConfig()
{
	CAAPuiPRDWorkshopConfigTRACE("CAAPuiPRDWorkshopConfig - Constructor");
}

//-----------------------------------------------------------------------------
// CAAPuiPRDWorkshopConfig : destructor
//-----------------------------------------------------------------------------
CAAPuiPRDWorkshopConfig::~CAAPuiPRDWorkshopConfig()
{
	CAAPuiPRDWorkshopConfigTRACE("CAAPuiPRDWorkshopConfig - Destructor");
}
 
//-----------------------------------------------------------------------------
// Implements CATIWorkbench::CreateWorkbench
//-----------------------------------------------------------------------------
CATCmdWorkbench *CAAPuiPRDWorkshopConfig::CreateWorkbench()
{
	CAAPuiPRDWorkshopConfigTRACE(">> CAAPuiPRDWorkshopConfig::CreateWorkbench()");
   
	// Definition of the CAAPuiPRDWorkshopConfig workbench Layout   
	NewAccess(CATCmdWorkbench, pWorkbench, CAAPuiPRDWorkshopConfig);

	//  Workbench Toolbar  
	NewAccess(CATCmdContainer, pToolbar, CAAPuiPRDWorkshopConfigToolbar);
	SetAccessChild(pWorkbench, pToolbar);
	
	// Add commands to toolbar
	NewAccess(CATCmdStarter, pStarter, CAAPuiPRDWorkshopConfigStarter);
	SetAccessCommand(pStarter, "CAAPuiPRDWorkshopConfigCmd1");
	SetAccessChild(pToolbar, pStarter);
 

	// Visible toolbar set in the right side of the application window
	int visibleFlag = 1;
	AddToolbarView(pToolbar, visibleFlag, Right);
 

	CAAPuiPRDWorkshopConfigTRACE("<< CAAPuiPRDWorkshopConfig::CreateWorkbench()");
	return pWorkbench;
}

//-----------------------------------------------------------------------------
// Implements CATIWorkbench::CreateCommands
//-----------------------------------------------------------------------------
void CAAPuiPRDWorkshopConfig::CreateCommands()
{
	CAAPuiPRDWorkshopConfigTRACE(">> CAAPuiPRDWorkshopConfig::CreateCommands()");   

	// Instantiates the command header for the command
	new CAAPuiPRDWorkshopConfigHeader("CAAPuiPRDWorkshopConfigCmd1",
					  "CAAPuiPRDWorkshopConfig",
					  "CAAPuiPRDWorkshopConfigCmd",
					  (void *)NULL);

	CAAPuiPRDWorkshopConfigTRACE("<< CAAPuiPRDWorkshopConfig::CreateCommands()");
}

//-----------------------------------------------------------------------------
// Implements CATIWorkbench::GetAddinInterface
//-----------------------------------------------------------------------------
CATClassId CAAPuiPRDWorkshopConfig::GetAddinInterface ()
{
	// Returns the interface name to implement an Addin to this workbench. 
	return "CAAIPuiPRDWorkshopConfigAddin";
}

//-----------------------------------------------------------------------------
// Implements CATIWorkbench::GetCustomInterfaces
//-----------------------------------------------------------------------------
void CAAPuiPRDWorkshopConfig::GetCustomInterfaces (CATListPV *iDefaultIIDList,
						   CATListPV *iCustomIIDList)
{
	// should be empty!
}

