// COPYRIGHT Dassault Systemes 2007
//===================================================================
//
// CATIEhfUIPArrangeJunction.h
// Define the CATIEhfUIPArrangeJunction interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  February 2007  Creation: Code generated by the CAA wizard  JNT
//===================================================================


#ifndef CAAEhfUIPArrangeJunction_h
#define CAAEhfUIPArrangeJunction_h

// --- System Framework ---
#include "CATBaseUnknown.h"

// --- ObjectModelerBase Framework ---
#include "sequence_CATBaseUnknown_ptr.h"

// --- Mathematics Framework ---
#include "CATLISTP_CATMathVector.h"

class CATMathPlane;

class CAAEhfUIPArrangeJunction : public CATBaseUnknown
{
  CATDeclareClass;
public:
  CAAEhfUIPArrangeJunction();
  virtual ~CAAEhfUIPArrangeJunction();
  HRESULT RetrieveUserDirection(const CATListPtrCATBaseUnknown & iListOfBundleSegmentExtremity, 
                                const CATMathPlane             & iFlatteningPlane,
                                CATLISTP(CATMathVector)        & ioListOfDirections);
 private:

  CAAEhfUIPArrangeJunction(const CAAEhfUIPArrangeJunction& );
  CAAEhfUIPArrangeJunction& operator=(const CAAEhfUIPArrangeJunction& );

};
#endif
