#======================================================================
# COPYRIGHT DASSAULT SYSTEMES 2003+
#======================================================================
# Imakefile for module CAAStrCreateObjects.m
#======================================================================
#
#  Jul 2003  Creation: Code generated by the CAA wizard  (Brian Yin)
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 
 
LINK_WITH = CATProductStructure1 \
            CATObjectModelerBase \
            JS0GROUP \
						CATStrInterfaces \
						YP00IMPL \
						CATMathematics \
						CATSketcherInterfaces \
						AC0SPBAS \
						KnowledgeItf \
						StructureInterfacesUUID \
						MecModItfCPP \
						MMInterfaces \
						CATGitInterfaces \
						CATVisualization \
						CATMatItfCPP \
						CATPspUUID \
						AS0AUTO \
						ProductStructurePubIDL
	

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
