/**
* @quickReview CRE 04:03:02
*/
//=============================================================================
//
// COPYRIGHT DASSAULT SYSTEMES  2001
//
// Sample code for : Geometric Modeler
// Mission         : Use of the Basic Topological Operators framework
//
// Type            : Batch program
// Inputs          : None
// Outputs         : Return codes (if not null, the model is not saved)
//                   0- OK
//                   1- Null pointer
//
// Coding steps    : 1- Create the geometry factory 
//                   2- Create the wire on which a CATMathPoint is 
//                      to be computed then created
//                   3- Create and use the CATComputeTopOnWire operator
//                      a - create the operator
//                      b - run it
//                   4- Create the cartesian point associated with the retrieved point      
//                   5- Clean unused objects
//                   6- Write the model 
//
// How to run it   : CAAComputePointOnWire           // to run whithout storing the NCGM file
//                   CAAComputePointOnWire file.NCGM // to run and store the result in file.NCGM                       
//=============================================================================

#include <iostream.h>
#include "fstream.h"

// Mathematics
#include "CATMathDirection.h"          // Mathematical unitary vector
#include "CATSoftwareConfiguration.h"  // Configuration of the operator
#include "CATMathAxis.h"               // Math axis creation
#include "CATMathPlane.h"          
#include "CATMathPoint.h"

// GeometricObjects
#include "CATGeoFactory.h"             // Geometry factory 
#include "CATCGMContainerMngt.h"       // Geometry factory management
#include "CATCurve.h"                  // Curve creation
#include "CATCrvLimits.h"              // Curve limits

// TopologicalObjects
#include "CATBody.h"                   // Body
#include "CATTopData.h"                // TopData of an operator

// BasicTopologicalOpe
#include "CATTopWire.h"                // Wire creation
#include "CATComputePointOnWire.h"     // Operator

//------------------------------------------------------------------------------
int main(int    iArgc,   // Number of arguments (0) or (1) 
         char** iArgv)   // Path to the *.NCGM document generated by the program
{
    int rc=0;
    if(2<iArgc) return (1);
	
    char *pfileName = NULL;
    int  toStore = 0;
    if (2==iArgc) 
    {
		toStore = 1; 
		pfileName = iArgv[1];
    }
	
	//----------------------------------------------------------------------------
	// 1 - Initialize the factory 
	//----------------------------------------------------------------------------
	
    CATGeoFactory* piGeomFactory = ::CATCreateCGMContainer() ;
	if (NULL==piGeomFactory) return (1);

	//----------------------------------------------------------------------------
	// 2 - Create the wire  
	//----------------------------------------------------------------------------
	
	// (a) --- Create a geometric circle
	//	
    CATMathPoint Absolute;
    CATMathDirection yDir(0.,1.,0.);
    CATMathDirection zDir(0.,0.,1.);
    CATMathPlane MathPlane(Absolute,yDir,zDir);

    double radius = 80.;
	double angleStart1 = CATPIBY2;
	double angleEnd1 = CAT3PIBY2;

    CATLONG32 nbcurve = 1;
    CATCurve ** ListOfCurves = new CATCurve * [nbcurve];

	CATCircle * piCircle = piGeomFactory->CreateCircle(radius, MathPlane,
		                                               angleStart1, angleEnd1);
	if (NULL==piCircle)
	{
	  ::CATCloseCGMContainer(piGeomFactory);
	  return (1);
	} 

    CATCurve * pLocalCurve = (CATCurve *)piCircle;
    //
    // (b) --- Create a wire from the geometric circle
	//
    // Define an open configuration for the operator
    CATSoftwareConfiguration * pConfig = new CATSoftwareConfiguration();
    // Define the data of the operator: configuration - no journal
    CATTopData topdata(pConfig);
    // Define the limits and orientations of the curves to be specified 
	CATCrvLimits CurLim[1];
    CATOrientation Orient[1]={1};
    pLocalCurve->GetLimits(CurLim[0]);
	ListOfCurves[0] = pLocalCurve;
    CATTopWire * pWire1 = ::CATCreateTopWire(piGeomFactory, 
		                                        &topdata,
											           1,
									        ListOfCurves,
									              CurLim,
											     Orient);
    if (NULL==pWire1)
    {
        ::CATCloseCGMContainer(piGeomFactory);
        return (1);
    }
    
    pWire1->Run();
    
    CATBody * pWireBody = pWire1->GetResult();
    if (NULL==pWireBody)
    {
        cout << "No valid result - NULL" << endl;
        ::CATCloseCGMContainer(piGeomFactory);
        return (1);
    }

	//----------------------------------------------------------------------------
	// 3 - Create the operator intended to compute a point
    //     at the middle of the wire - run the operator and
    //     retrieve the mathematical point
	//----------------------------------------------------------------------------
     
    CATComputePointOnWire* pPointOnWire = ::CATCreateComputePointOnWire(piGeomFactory,
        &topdata, 
        pWireBody,  0.5);
    if (NULL==pPointOnWire)
    {
        cout << "No valid result - NULL" << endl;
        ::CATCloseCGMContainer(piGeomFactory);
        return (1);
    }                                    
    
    CATMathPoint oPointOnWire;
    pPointOnWire->Run();
    pPointOnWire->GetMathPoint(oPointOnWire);
    
	//----------------------------------------------------------------------------
	// 4 - Create the cartesian point to be visualized at the computed point
    //     location
	//----------------------------------------------------------------------------
    //
    CATCartesianPoint* piCP1= piGeomFactory->CreateCartesianPoint(oPointOnWire);

   	//---------------------------------------------------------------------------
	// 5- Delete the operator
	//---------------------------------------------------------------------------
	//
	delete pWire1;
	pWire1 = NULL;
	//
	delete pPointOnWire;
	pPointOnWire = NULL;
	
	if (ListOfCurves) delete [] ListOfCurves;
    //---------------------------------------------------------------------------
	// 6 - Release the configuration
	//---------------------------------------------------------------------------
    //
	pConfig->Release();
	
	//---------------------------------------------------------------------------
	// 7 - Write the model and close the container
	//---------------------------------------------------------------------------
    if(1==toStore)
    {
#ifdef _WINDOWS_SOURCE
		ofstream filetowrite(pfileName, ios::binary ) ;
#else
		ofstream filetowrite(pfileName,ios::out,filebuf::openprot) ;
#endif
		
		::CATSaveCGMContainer(piGeomFactory,filetowrite);
		filetowrite.close();
    }	
	
    ::CATCloseCGMContainer(piGeomFactory);
	return (rc);
}

