//=============================================================================
//
// COPYRIGHT DASSAULT SYSTEMES  2001
//
// Sample code for : Geometric Modeler
// Mission         : Use of the TopologicalOperators framework
//
// Type            : Batch program
// Inputs          : None
// Outputs         : Return codes (if not null, the model is not saved)
//                   0- OK
//                   1- Null pointer
//
// Coding steps    : 1- Creation of the geometry factory
//                   2- Creation of the geometry (a prism from a spline)
//                   3- Create and use the CATTopSurToNurbsSurOperator
//                      a - create the operator
//                      b - tune the parameters
//                      c - run it
//                      d - get the result
//                   4- Deletion of the operator
//                   5- Writing the model 
//
// How to run it   : CAATopSurToNurbs           // to run whithout storing the NCGM file
//                   CAATopSurToNurbs file.NCGM // to run and store the result in file.NCGM                       
//=============================================================================

#include <iostream.h>
#include "fstream.h"

// Mathematics
#include "CATMathDirection.h"          // mathematical unitary vector
#include "CATSoftwareConfiguration.h"  // Configuration of the operator

// GeometricObjects
#include "CATGeoFactory.h"             // Geometry factory 
#include "CATCGMContainerMngt.h"       // Geometry factory management

// TopologicalObjects
#include "CATBody.h"                     // body
#include "CATTopData.h"                  // TopData of an operator

// TopologicalOperators
#include "CATTopPrism.h"                 // Prism creation
#include "CATTopPointOperator.h"         // To create point bodies
#include "CATTopSplineOperator.h"        // To create spline bodies
#include "CATTopSurToNurbsSurOperator.h" // To convert a surface to a Nurbs


//------------------------------------------------------------------------------
int main(int    iArgc,   // Number of arguments (0) or (1) 
         char** iArgv)   // Path to the *.NCGM document generated by the program
{
    int rc=0;
    if(2<iArgc) return (1);
	
    char *pfileName = NULL;
    int  toStore = 0;
    if (2==iArgc) 
    {
		toStore = 1; 
		pfileName = iArgv[1];
    }
	
	//----------------------------------------------------------------------------
	// 1 - Initialize the factory 
	//----------------------------------------------------------------------------
	
    CATGeoFactory* piGeomFactory = ::CATCreateCGMContainer() ;
	if (NULL==piGeomFactory) return (1);
	
	//----------------------------------------------------------------------------
	// 2 - Create the geometry 
	//----------------------------------------------------------------------------
	
	// (a) --- Create topological points
	//
	const int nbpts = 4;
	CATBody ** aPoints = new CATBody * [nbpts];
	
    CATSoftwareConfiguration * pConfig = new CATSoftwareConfiguration();
    CATTopData topdata(pConfig);
	
	aPoints[0] = ::CATCreateTopPointXYZ(piGeomFactory,&topdata,-20.,0., 0.);
	aPoints[1] = ::CATCreateTopPointXYZ(piGeomFactory,&topdata,-20.,5., 0);
	aPoints[2] = ::CATCreateTopPointXYZ(piGeomFactory,&topdata,-10.,5., 0.);
	aPoints[3] = ::CATCreateTopPointXYZ(piGeomFactory,&topdata,-10.,0., 0.);
	
    // (b) --- Create a spline body
	//   
	CATBody * piSplineBody = ::CATCreateTopSpline(piGeomFactory,
		&topdata,
		nbpts,
		aPoints);
    if (NULL==piSplineBody)
	{
		::CATCloseCGMContainer(piGeomFactory);
		return (1);
	}
	
    // (c) --- Create a prism
	// 
	CATMathDirection   zDir(0., 0., 1.);
	double startOffset = 10.;
    double endOffset   = 30.;
    CATTopPrism       *pPrismOp = ::CATCreateTopPrism (piGeomFactory,
		&topdata,
		piSplineBody,
		&zDir,
		startOffset,
		endOffset);
	
    if (NULL==pPrismOp)
    {
		::CATCloseCGMContainer(piGeomFactory);
		return (1);
    }
	
	// (d) --- Run the CATTopPrism operator
	//
    pPrismOp->Run();
	
    // (e) --- Get the result
	//
	CATBody * pPrismOp2 = pPrismOp->GetResult();
    if (NULL==pPrismOp2)
	{
		cout << "No valid result - NULL" << endl;
		::CATCloseCGMContainer(piGeomFactory);
		return (1);
	}
	
	// (f) --- Retrieve the number of faces
	//
	CATLISTP(CATCell) listCells;
	pPrismOp2->GetAllCells(listCells, 2 );
	
	// (g) --- Check the number of faces (1 is expected for the spline)
	//
	int nbCells = listCells.Size();
	cout << "The face number is : " << nbCells << endl; 
	
    //----------------------------------------------------------------------------
	// 3 - Create and use the CATTopSurToNurbsSurOperator operator 
	//----------------------------------------------------------------------------
	
	// (a) --- Create the operator
	//
	CATTopSurToNurbsSurOperator * pSurToNurbsOp = ::CATCreateTopSurToNurbsSurOperator(piGeomFactory,
		&topdata,
		pPrismOp2,
		listCells[1]);
	if (NULL==pSurToNurbsOp)
	{
		cout << "No operator created" << endl;
		::CATCloseCGMContainer(piGeomFactory);
		return (1);
	}
	
	// (b) --- Tune the parameters
	// Warning: Depending on the parameter values, the result may or may 
	// not be valid. 
	
	pSurToNurbsOp->SetMaxDegreeU(2);
	pSurToNurbsOp->SetMaxDegreeV(2);
	pSurToNurbsOp->SetMaxArcsU(1);
	pSurToNurbsOp->SetMaxArcsV(1);
	pSurToNurbsOp->SetRationalAbility(0);
	
	
	// (c) --- Runs the CATTopSurToNurbsSurOperator operator
	//
	pSurToNurbsOp->Run();
	
	
	// (d) --- Get the result
	//
	CATBody * pSurToNurbsOp2 = pSurToNurbsOp->GetResult();
    if (NULL==pSurToNurbsOp2)
	{
		cout << "No valid result - NULL" << endl;
		::CATCloseCGMContainer(piGeomFactory);
		return (1);
	}
   	//---------------------------------------------------------------------------
	// 4 - Delete the operator
	//---------------------------------------------------------------------------
	
	delete pPrismOp;
	pPrismOp = NULL;
	
	delete pSurToNurbsOp;
	pSurToNurbsOp = NULL;
	
	if (aPoints) delete [] aPoints;
    //---------------------------------------------------------------------------
	// 5 - Release the configuration
	//---------------------------------------------------------------------------
    
	pConfig->Release();
	
	//---------------------------------------------------------------------------
	// 6 - Write the model and close the container
	//---------------------------------------------------------------------------
    if(1==toStore)
    {
#ifdef _WINDOWS_SOURCE
		ofstream filetowrite(pfileName, ios::binary ) ;
#else
		ofstream filetowrite(pfileName,ios::out,filebuf::openprot) ;
#endif
		
		::CATSaveCGMContainer(piGeomFactory,filetowrite);
		filetowrite.close();
    }	
	
    ::CATCloseCGMContainer(piGeomFactory);
	return (rc);
}

