// COPYRIGHT DASSAULT SYSTEMES 1994-2000
//===================================================================
//
// CAAIOmmVertLine.idl
// Automation interface for the OmmVerticalLine element 
//
//===================================================================
#ifndef CAAIOmmVertLine_IDL
#define CAAIOmmVertLine_IDL

#include "CATIAHybridShape.idl"
#include "CATIAReference.idl"

// Interface modeling the CATOmmVerticalLine behaviors
interface CAAIAOmmVerticalLine : CATIAHybridShape 
{
        // Property setting the first line point given as a reference, i.e.
		// a concrete point or a vertex
#pragma PROPERTY Point1
  
        HRESULT get_Point1(out /*IDLRETVAL*/ CATIAReference opiReferenceOnPoint1);
        HRESULT put_Point1(in CATIAReference ipiReferenceOnPoint1);

        // Property setting the limiting vertical line point given as a reference,
		// i.e. a concrete point or a vertex
#pragma PROPERTY Point2
     
        HRESULT get_Point2(out /*IDLRETVAL*/ CATIAReference opiReferenceOnPoint2);
        HRESULT put_Point2(in CATIAReference ipiReferenceOnPoint2);
};

// Interface name : CAAIOmmVerticalLine
#pragma ID CAAIAOmmVerticalLine "DCE:2ea944f0-1539-11d4-9eea00508b675465"
#pragma DUAL CAAIAOmmVerticalLine

// VB object name : OmmVerticalLine (Id used in Visual Basic)
#pragma ID OmmVerticalLine "DCE:2ea944f1-1539-11d4-9eea00508b675465"
#pragma ALIAS CAAIAOmmVerticalLine OmmVerticalLine

#endif
