// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CAAPuiPrsConfigAddinCmd.cpp
// The command: CAAPuiPrsConfigAddinCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Sep 2003  Creation: Code generated by the CAA wizard  avm
//===================================================================
#include "CAAPuiPrsConfigAddinCmd.h"
#include "CAAPuiPrsConfigAddinTrace.h"

// ApplicationFrame framework
#include "CATApplicationFrame.h"

// Dialog framework
#include "CATDlgNotify.h"

#include "CATCreateExternalObject.h"
CATCreateClass( CAAPuiPrsConfigAddinCmd);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
CAAPuiPrsConfigAddinCmd::CAAPuiPrsConfigAddinCmd():
	CATCommand(NULL, "CAAPuiPrsConfigAddinCmd")
{
	RequestStatusChange (CATCommandMsgRequestExclusiveMode);
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
CAAPuiPrsConfigAddinCmd::~CAAPuiPrsConfigAddinCmd()
{
}


// Activates our command.
//   iFromClient :The command that requests to activate the current one.
//   iEvtDat :The notification sent.
// ----------------------------------------------------
CATStatusChangeRC CAAPuiPrsConfigAddinCmd::Activate(CATCommand *iFromClient,
						    CATNotification * iEvtDat)
{
	CAAPuiPrsConfigAddinTRACE (">> CAAPuiPrsConfigAddinCmd::Activate");

	CATApplicationFrame *pApplication = CATApplicationFrame::GetFrame(); 
	if (NULL != pApplication) { 		
 		CATDlgWindow * pMainWindow = NULL;
		pMainWindow = pApplication->GetMainWindow();
		CATDlgNotify *pNotifyDlg = new CATDlgNotify
			(pMainWindow, "CAAPuiPrsConfigAddin", CATDlgNfyOK);
		if (NULL != pNotifyDlg) {
			pNotifyDlg->DisplayBlocked
				("Hello World!",
				 "CAAPuiPrsConfigAddin UseCase");
			pNotifyDlg->RequestDelayedDestruction(); 
		}
	}
	RequestDelayedDestruction(); 

	CAAPuiPrsConfigAddinTRACE ("<< CAAPuiPrsConfigAddinCmd::Activate");
	return CATStatusChangeRCCompleted;
}
