// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CAAPuiPrsConfigAddin.cpp
// Provide implementation to interface
//    CATIWorkbenchAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Sep 2003  Creation: Code generated by the CAA wizard  avm
//===================================================================
#include "CAAPuiPrsConfigAddin.h"
#include "CAAPuiPrsConfigAddinHeader.h"
#include "CAAPuiPrsConfigAddinTrace.h"

// ApplicationFrame framework
#include "CATCreateWorkshop.h"

// ProductStructureUI framework
#include "CATIPrsConfigurationAddin.h"
 
CATImplementClass(CAAPuiPrsConfigAddin,
		  Implementation,
		  CATBaseUnknown,
		  CATnull);
 
// Tie the implementation to its interface
// ---------------------------------------
#include "TIE_CATIPrsConfigurationAddin.h"
TIE_CATIPrsConfigurationAddin(CAAPuiPrsConfigAddin);

//-----------------------------------------------------------------------------
// CAAPuiPrsConfigAddin : constructor
//-----------------------------------------------------------------------------
CAAPuiPrsConfigAddin::CAAPuiPrsConfigAddin():
	CATBaseUnknown()
{
	CAAPuiPrsConfigAddinTRACE("CAAPuiPrsConfigAddin - Constructor");   
}

//-----------------------------------------------------------------------------
// CAAPuiPrsConfigAddin : destructor
//-----------------------------------------------------------------------------
CAAPuiPrsConfigAddin::~CAAPuiPrsConfigAddin()
{
	CAAPuiPrsConfigAddinTRACE("CAAPuiPrsConfigAddin - Destructor");   
}
 
//-----------------------------------------------------------------------------
// Implements CATIWorkbenchAddin::CreateCommands
//-----------------------------------------------------------------------------
void CAAPuiPrsConfigAddin::CreateCommands()
{
	CAAPuiPrsConfigAddinTRACE(">> CAAPuiPrsConfigAddin::CreateCommands()");
	
	// Instantiates the command header for the command
	new CAAPuiPrsConfigAddinHeader
		("CAAPuiPrsConfigAddinCmd1",	// command name
		 "CAAPuiPrsConfigAddin",	// lib name
		 "CAAPuiPrsConfigAddinCmd",	// class name
		 (void *)NULL);

	CAAPuiPrsConfigAddinTRACE("<< CAAPuiPrsConfigAddin::CreateCommands()");
}

//-----------------------------------------------------------------------------
// Implements CATIWorkbenchAddin::CreateToolbars
//-----------------------------------------------------------------------------
CATCmdContainer *CAAPuiPrsConfigAddin::CreateToolbars()
{
	CAAPuiPrsConfigAddinTRACE(">> CAAPuiPrsConfigAddin::CreateToolbars()");

	// Declaration of toolbar for Addin
	NewAccess(CATCmdContainer, pToolbarContainer,
		  CAAPuiPrsConfigAddinToolbar);
	NewAccess(CATCmdStarter, pCommandStarter,
		  CAAPuiPrsConfigAddinStarter);

	// Arranging the command within the toolbar
	SetAccessCommand(pCommandStarter, "CAAPuiPrsConfigAddinCmd1");
	SetAccessChild(pToolbarContainer, pCommandStarter);

	int visibleFlag = 1;
	AddToolbarView(pToolbarContainer, visibleFlag, Top);
   
	CAAPuiPrsConfigAddinTRACE("<< CAAPuiPrsConfigAddin::CreateToolbars()");
	return pToolbarContainer;
}

