# COPYRIGHT DASSAULT SYSTEMES 2002
#======================================================================
# Imakefile for module CAATPEDisplayToolPathCommand.m
#======================================================================
#
#  Jan 2002  Creation: Code generated by the CAA wizard 
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
LINK_WITH = CD0WIN JS0FM JS0GROUP \
		    CATViz CATToolPathEditorInterfaces

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
