// COPYRIGHT Dassault Systemes 2004
//===================================================================
//
// CAAGetFLEXEquivalentModulusExt.h
// Provide implementation to interface
//    CATIEhiFLEX
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   EXTENSION: ElecBranchableC
//   TIE: CATIEhiFLEX
//End CAA2 Wizard Generation Report
//
//  Sep 2004  Creation: Code generated by the CAA wizard  axc
//===================================================================
#ifndef CAAGetFLEXEquivalentModulusExt_H
#define CAAGetFLEXEquivalentModulusExt_H

#include "CATBaseUnknown.h"

#include "CATIEhiFLEX.h"

class CATListValCATBaseUnknown_var;
//-----------------------------------------------------------------------

/**
 * Class extending the object "ElecBranchableC".
 * <br>
 * It implements the interfaces :
 *  <ol>
 *  <li>@see ElecHarnessItf.CATIEhiFLEX
 *  </ol>
 * Using this prefered syntax will enable mkdoc to document your class.
 */
class CAAGetFLEXEquivalentModulusExt: public CATBaseUnknown
{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     CAAGetFLEXEquivalentModulusExt ();
     virtual ~CAAGetFLEXEquivalentModulusExt ();

    /**
	 * Implements the method GetFLEXEquivalentModulus from the interface
	 * CATIEhiFLEX
	 *
     * Returns the value of the Equivalent Young Modulus (in N/m2) and 
     * Equivalent RatioToBend and Equivalent RatioToTwist function of
     * the values of the wires/wiregroups and  protections contained 
     * in it. Also function of the profile type and dimensions of the
	 * segment, and the flexibility of the bundle segment.
	 *
     * @param iListOfWireWireGroup
     *   The list of the Wire(s) and/or WireGroup(s) in the segment.
     *  
	 * @param iOrderedListOfProtectionReference
     *   The list of the Protections(s) covering successively the segment.
	 *
	 * @param ipInternalSpliceReferenceList
     *   The list of the Internal Splice(s) inside the the segment.
	 *
	 * @param iProfileLength1
     *   The major dimension of the profile (in mm).
	 *
     * @param iProfileLength2
     *   The minor dimension of the profile (in mm).
	 *
     * @param iBundleSegmentFlexibility
     *   The list of the Protections(s) covering successively the segment.
	 *
     * @param oYoungModulusEquivalent
     *   The value of the equivalent Young Modulus (in N/m2) of the segment.
	 *
     * @param oEquivalentRatioToBend
     *   The value of the equivalent Ratio-To-Bend of the segment.
	 *
     * @param oEquivalentRatioToTwist
     *   The value of the equivalent Ratio-To-Twist of the segment.
     */
     HRESULT GetFLEXEquivalentModulus (CATListValCATBaseUnknown_var *  ipListOfWireWireGroup  , CATListValCATBaseUnknown_var *  ipOrderedListOfProtectionReference  , CATListValCATBaseUnknown_var * ipInternalSpliceReferenceList, CATEhiProfileType  iProfile  , double  iProfileLength1  , double  iProfileLength2  , int  iBundleSegmentFlexibility  , double & oYoungModulusEquivalent  , double & oEquivalentRatioToBend  , double & oEquivalentRatioToTwist ) ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  CAAGetFLEXEquivalentModulusExt (CAAGetFLEXEquivalentModulusExt &);
  CAAGetFLEXEquivalentModulusExt& operator=(CAAGetFLEXEquivalentModulusExt&);

};

//-----------------------------------------------------------------------

#endif
