// COPYRIGHT DASSAULT SYSTEMES 2002
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework CAASurfaceMachiningItf.edu
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Jan 2002  Creation: Code generated by the CAA wizard  gvs
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("ManufacturingInterfaces",Public);
AddPrereqComponent("SurfaceMachiningInterfaces",Public);

AddPrereqComponent("ApplicationFrame",Public);
AddPrereqComponent("Dialog",Public);
AddPrereqComponent("DialogEngine",Public);
AddPrereqComponent("DMAPSInterfaces",Public);
AddPrereqComponent("GeometricObjects",Public);
AddPrereqComponent("KnowledgeInterfaces",Public);
AddPrereqComponent("LiteralsEditor",Public);
AddPrereqComponent("LiteralFeatures",Public);
AddPrereqComponent("Mathematics",Public);
AddPrereqComponent("MechanicalModeler",Public);
AddPrereqComponent("ConstraintModeler",Public);
AddPrereqComponent("ConstraintModelerInterfaces",Public);
AddPrereqComponent("ObjectModelerBase",Public);
AddPrereqComponent("ObjectSpecsModeler",Public);
AddPrereqComponent("PartInterfaces",Public);
AddPrereqComponent("ProductStructure",Public);
AddPrereqComponent("System",Public);
AddPrereqComponent("Tessellation",Public);
AddPrereqComponent("Visualization",Public);
AddPrereqComponent("VisualizationBase",Public);
AddPrereqComponent("MecModInterfaces",Public);
AddPrereqComponent("NewTopologicalObjects",Public);
// END WIZARD EDITION ZONE
