#ifndef CAAIASysSprocket_idl
#define CAAIASysSprocket_idl


// COPYRIGHT DASSAULT SYSTEMES 2002

#include "CATIABase.idl"

/**
 * Interface to describe a Sprocket (whatever that is) object
 */
interface CAAIASysSprocket : CATIABase {
};

// Interface name : CAAIASysSprocket
#pragma ID CAAIASysSprocket "DCE:a5efde80-2f74-11d6-804d0010b5fa1031"							 	
#pragma DUAL CAAIASysSprocket

// VB object name : Sprocket
#pragma ID Sprocket "DCE:a68a3470-2f74-11d6-804d0010b5fa1031"
#pragma ALIAS CAAIASysSprocket Sprocket

#endif // CAAIASysSprocket_idl

