# COPYRIGHT DASSAULT SYSTEMES 2003
#======================================================================
# Imakefile for module CAAV4iEduModelScan.m
#======================================================================
#
#  Jul 2003  Creation: Code generated by the CAA wizard  nbl
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 

LINK_WITH = JS0GROUP CATV4iInterface CATV4iPipeInterface CATV4iServices \
                        CATObjectModelerCATIA      \
                        CATObjectModelerBase       

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
