// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CAAPuiPrsConfigAddinCmd.h
// The command: CAAPuiPrsConfigAddinCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Sep 2003  Creation: Code generated by the CAA wizard  avm
//===================================================================
#ifndef CAAPuiPrsConfigAddinCmd_H
#define CAAPuiPrsConfigAddinCmd_H

#include "CATCommand.h"

//----------------------------------------------------------------------

/**
 * Command for the CAAPuiPrsConfigAddin use case
 */
class CAAPuiPrsConfigAddinCmd: public CATCommand {

public:

	CAAPuiPrsConfigAddinCmd();
	virtual ~CAAPuiPrsConfigAddinCmd();

 	/**
	 * Activates our command.
	 * @param iFromClient 
	 *   The command that requests to activate the current one.
	 * @param iEvtDat
	 *   The notification sent.
	 */
	virtual CATStatusChangeRC Activate(CATCommand * iFromClient,
					   CATNotification * iEvtDat);

};

//----------------------------------------------------------------------

#endif
