// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CAAPuiPrsConfigAddin.h
// Provide implementation to interface
//    CATIWorkbenchAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Sep 2003  Creation: Code generated by the CAA wizard  avm
//===================================================================
#ifndef CAAPuiPrsConfigAddin_H
#define CAAPuiPrsConfigAddin_H

#include "CATBaseUnknown.h"

//-----------------------------------------------------------------------

/**
 * Class Object modeler implementation class.
 * <br>
 * It implements the interfaces :
 *  <ol>
 *  <li>CATIPrsConfigurationAddin @see ApplicationFrame.CATIWorkbenchAddin
 *  </ol>
 */
class CATCmdContainer;

class CAAPuiPrsConfigAddin: public CATBaseUnknown {
	
CATDeclareClass;

public:

	// Standard constructors and destructors for an implementation class
	// -----------------------------------------------------------------
	CAAPuiPrsConfigAddin();
	virtual ~CAAPuiPrsConfigAddin();

	/**
	 * @see ApplicationFrame.CATIWorkbenchAddin#CreateCommands
	 */
	void CreateCommands();

	/**
	 * @see ApplicationFrame.CATIWorkbenchAddin#CreateToolbars
	 */
	CATCmdContainer *CreateToolbars();


private:
	// The copy constructor and the equal operator must not be implemented
	// -------------------------------------------------------------------
	CAAPuiPrsConfigAddin (CAAPuiPrsConfigAddin &);
	CAAPuiPrsConfigAddin& operator=(CAAPuiPrsConfigAddin&);

};

//-----------------------------------------------------------------------

#endif
