/**
* @quickReview CRE 03:10:17
*/
//=============================================================================
//
// COPYRIGHT DASSAULT SYSTEMES  2002
//
// Sample code for : Geometric Modeler
// Mission         : Explains how to create a circle sweep with three guides
//           
// Type            : Batch program
// Inputs          : None
// Outputs         : Return codes (if not null, the model is not saved)
//                   0- OK
//                   1- Null pointer
//
// Main steps        1- Create the geometry factory and other preliminary operations
//                   2- Create the three guides
//                   3- Create the sweep circle
//                   4- Write the model and close the container  
//
// How to run it   : CAAAdtCircleSweepThreeGuides    // to run whithout storing the NCGM file
//                   CAAAdtCircleSweepThreeGuides file.NCGM // to run and store the result 
//                   in file.NCGM     
//=============================================================================

#include <iostream.h>
#include <iomanip.h>
#include "fstream.h"

// Mathematics
#include "CATMathAxis.h"                 // Math axis creation
#include "CATMathPlane.h"                // Math plane creation
#include "CATMathPoint.h"

// Advanced Mathematics
#include "CATMathSetOfPointsND.h"        // Creation of a set of points
#include "CATSoftwareConfiguration.h"

// GeometricObjects
#include "CATGeoFactory.h"               // Geometry factory
#include "CATCGMContainerMngt.h"         // Management of the geometry factory
#include "CATSplineCurve.h"              // Spline creation
#include "CATCrvLimits.h"                // Curve limits
  
// TopologicalOperators
#include "CATTopPrism.h"                 // To extrude a curve
#include "CATTopWire.h"                  // To create a wire

// AdvancedtopologicalOpe
#include "CATFrFTopologicalSweep.h"      // The sweep operator
#include "CreateFrFTopologicalSweep.h"   // To create the sweep operator

// NewTopologicalObjects
#include "CATBody.h"                       // Body
#include "ListPOfCATBody.h"                // List of bodies

// ---------------------------------------------------------------------------
int main(int    iArgc,   // Number of arguments (0) or (1) 
         char** iArgv)   // Path to the *.NCGM document generated by this program
{
    int rc=0;
    if(2<iArgc) return (1);
    
    char *pFileName = 0;
    int  toStore = 0;
    if (2==iArgc) 
    {
        toStore = 1; 
        pFileName = iArgv[1];
    }
    
    //----------------------------------------------------------------------------
    // 1 - Preliminary operations
    //----------------------------------------------------------------------------
    //
    // a - Factory 
    //
    CATGeoFactory* piGeomFactory = ::CATCreateCGMContainer() ;
    if (NULL==piGeomFactory) return (1);
    
    // b - Journal and configuration
    //
    CATSoftwareConfiguration * pConfig = new CATSoftwareConfiguration();
    CATTopData topdata(pConfig, NULL);
    
    // -----------------------------------------------------------------------------
    // 2 - Create the guides (3 splines )
    // -----------------------------------------------------------------------------
    
    // ---- (a) Specify the points 
    //
    CATMathSetOfPointsND pointSet1(3,3);  // Spline 1
    CATMathSetOfPointsND pointSet2(3,3);  // Spline 2
    CATMathSetOfPointsND pointSet3(3,3);  // Spline 3
    
    // ---- (b) Specify the points to be used for the splines
    //
    double Point1[3]={ 0.0,  0.0,  0.0} ;
    double Point2[3]={ 0.0, 41.0,  3.0} ;
    double Point3[3]={ 0.0, 93.0, -6.0} ;
    double Point4[3]={10.0,  0.0,  0.0} ;
    double Point5[3]={10.0, 44.0, -3.0} ;
    double Point6[3]={10.0, 98.0, -2.0} ;
    double Point7[3]={5.0,  0.0,  -10.0} ;
    double Point8[3]={5.0, 44.0, -8.0} ;
    double Point9[3]={5.0, 98.0, -12.0} ;

    
    // ---- (c) Create the spline 1
    //
    pointSet1.AddPoint(Point1); // Point1
    pointSet1.AddPoint(Point2); // Point2
    pointSet1.AddPoint(Point3); // Point3
    
    double param1[3];
    param1[0] = 0.;
    param1[1] = 1.;
    param1[2] = 2.;
    
    CATSplineCurve * piSpline1 = piGeomFactory->CreateSplineCurve(&pointSet1,0,1,2,param1);
    if (NULL==piSpline1)
    {
        ::CATCloseCGMContainer(piGeomFactory);
        return (1);
    }
    CATCurve * piCurve1 = (CATCurve*)piSpline1;
    
    // ---- (d) Create the spline 2
    //
    pointSet2.AddPoint(Point4); //Point4
    pointSet2.AddPoint(Point5); //Point5
    pointSet2.AddPoint(Point6); //Point6	
    
    double param2[3];
    param2[0] = 0.;
    param2[1] = 1.;
    param2[2] = 2.;
    
    CATSplineCurve * piSpline2 = piGeomFactory->CreateSplineCurve(&pointSet2,0,1,2,param2);
    if (NULL==piSpline2)
    {
        ::CATCloseCGMContainer(piGeomFactory);
        return (1);
    }
    CATCurve * piCurve2 = (CATCurve*)piSpline2;

     // ---- (c) Create the spline 3
    //
    pointSet3.AddPoint(Point7); // Point1
    pointSet3.AddPoint(Point8); // Point2
    pointSet3.AddPoint(Point9); // Point3
    
    double param3[3];
    param3[0] = 0.;
    param3[1] = 1.;
    param3[2] = 2.;
    
    CATSplineCurve * piSpline3 = piGeomFactory->CreateSplineCurve(&pointSet3,0,1,2,param3);
    if (NULL==piSpline3)
    {
        ::CATCloseCGMContainer(piGeomFactory);
        return (1);
    }
    CATCurve * piCurve3 = (CATCurve*)piSpline3;
    
    // ---- (e) Create the wire 1
    //
    CATLONG32 nbcurve1 = 1;
    CATCurve * ListOfCurves1;
    
    ListOfCurves1 = piCurve1;
    CATCrvLimits CurLim1[1];
    CATOrientation Orient1[1]={1};
    ListOfCurves1->GetLimits(CurLim1[0]);
    CATTopWire * pWire1 = CATCreateTopWire(piGeomFactory, 
        &topdata,
        1,
        &ListOfCurves1,
        CurLim1,
        Orient1);
    if (NULL==pWire1)
    {
        ::CATCloseCGMContainer(piGeomFactory);
        return (1);
    }
    
    pWire1->Run();
    
    CATBody * pWireBody1 = pWire1->GetResult();
    if (NULL==pWireBody1)
    {
        cout << "No valid result - NULL" << endl;
        ::CATCloseCGMContainer(piGeomFactory);
        return (1);
    }   
    delete pWire1;
    pWire1 = NULL;
    
    // ---- (f) Create the wire 2
    //
    CATLONG32 nbcurve2 = 1;
    CATCurve * ListOfCurves2;
    
    ListOfCurves2 = piCurve2;
    CATCrvLimits CurLim2[1];
    CATOrientation Orient2[1]={1};
    ListOfCurves2->GetLimits(CurLim2[0]);
    CATTopWire * pWire2 = CATCreateTopWire(piGeomFactory, 
        &topdata,
        1,
        &ListOfCurves2,
        CurLim2,
        Orient2);
    if (NULL==pWire2)
    {
        ::CATCloseCGMContainer(piGeomFactory);
        return (1);
    }
    
    pWire2->Run();
    
    CATBody * pWireBody2 = pWire2->GetResult();
    if (NULL==pWireBody2)
    {
        cout << "No valid result " << endl;
        ::CATCloseCGMContainer(piGeomFactory);
        return (1);
    }   
    delete pWire2;
    pWire2 = NULL;


    // ---- (f) Create the wire 3
    //
    CATLONG32 nbcurve3 = 1;
    CATCurve * ListOfCurves3;
    
    ListOfCurves3 = piCurve3;
    CATCrvLimits CurLim3[1];
    CATOrientation Orient3[1]={1};
    ListOfCurves3->GetLimits(CurLim3[0]);
    CATTopWire * pWire3 = CATCreateTopWire(piGeomFactory, 
        &topdata,
        1,
        &ListOfCurves3,
        CurLim3,
        Orient3);
    if (NULL==pWire3)
    {
        ::CATCloseCGMContainer(piGeomFactory);
        return (1);
    }
    
    pWire3->Run();
    
    CATBody * pWireBody3 = pWire3->GetResult();
    if (NULL==pWireBody3)
    {
        cout << "No valid result" << endl;
        ::CATCloseCGMContainer(piGeomFactory);
        return (1);
    }   
    delete pWire3;
    pWire3 = NULL;
    
    // -----------------------------------------------------------------------------
    // 3 - Create the sweep circle (3 guides )
    // -----------------------------------------------------------------------------
    
    CATLISTP(CATGeometry) guides0;
    CATGeometry * guideGeom1 = (CATGeometry*)pWireBody1 ;
    CATGeometry * guideGeom2 = (CATGeometry*)pWireBody2 ;
    CATGeometry * guideGeom3 = (CATGeometry*)pWireBody3 ;
    guides0.Append(guideGeom1);
    guides0.Append(guideGeom3);
    guides0.Append(guideGeom2);
    
    // (a) - Creation of the sweep operator
    //
    CATFrFTopologicalSweep * pSweepOpe = CATCreateFrFTopologicalCircleSweep(piGeomFactory, 
        &topdata, &guides0);
    if (NULL==pSweepOpe)
    {
        cout << "pb when creating the sweep operator " << endl;
        ::CATCloseCGMContainer(piGeomFactory);
        return (1);
    }
    
    // (b) - Run the operator
    //
    pSweepOpe -> Run();

    // (c) - Get the result
    //
    CATBody * pBodySweepCircle  = pSweepOpe->GetResult();
    
    // (d) - Delete the operator
    //
    delete pSweepOpe;
    pSweepOpe = NULL;

    piGeomFactory->Remove(pWireBody1);
    piGeomFactory->Remove(pWireBody2);
    piGeomFactory->Remove(pWireBody3);

    pConfig->Release();    // Release the configuration

    //----------------------------------------------------------------------------
    // 4 - Save the model
    //----------------------------------------------------------------------------
    
    if(1==toStore)
    {
        cout << "Writing the model" << endl;
#ifdef _WINDOWS_SOURCE
        ofstream filetowrite(pFileName, ios::binary ) ;
#else
        ofstream filetowrite(pFileName,ios::out,filebuf::openprot) ;
#endif
        
        ::CATSaveCGMContainer(piGeomFactory,filetowrite);
        filetowrite.close();
    }	
    
    ::CATCloseCGMContainer(piGeomFactory);
    return (rc);
}


