// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CAAIPuiPRDWorkshopConfigAddin.h
// Define the CAAIPuiPRDWorkshopConfigAddin interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Sep 2003  Creation: Code generated by the CAA wizard  avm
//===================================================================
#ifndef CAAIPuiPRDWorkshopConfigAddin_H
#define CAAIPuiPRDWorkshopConfigAddin_H

#include "CAAPuiPRDWorkshopConfig.h"
#include "CATIWorkbenchAddin.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern IID IID_CAAIPuiPRDWorkshopConfigAddin;
#else
extern "C" const IID IID_CAAIPuiPRDWorkshopConfigAddin ;
#endif

//------------------------------------------------------------------

class CAAIPuiPRDWorkshopConfigAddin: public CATIWorkbenchAddin
{
	CATDeclareInterface;
public:				// this is required by the TIE compiler

};

//------------------------------------------------------------------

#endif
