// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CAAIPuiPRDWorkshopConfigFactory.h
// Define the CAAIPuiPRDWorkshopConfigFactory interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Sep 2003  Creation: Code generated by the CAA wizard  avm
//===================================================================
#ifndef CAAIPuiPRDWorkshopConfigFactory_H
#define CAAIPuiPRDWorkshopConfigFactory_H

#include "CATIGenericFactory.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern IID IID_CAAIPuiPRDWorkshopConfigFactory;
#else
extern "C" const IID IID_CAAIPuiPRDWorkshopConfigFactory ;
#endif

//------------------------------------------------------------------

/**
 * Describe the functionality of your interface here
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 */
class CAAIPuiPRDWorkshopConfigFactory: public CATIGenericFactory
{
  CATDeclareInterface;

  public:

    /**
     * Remember that interfaces define only virtual pure methods.
     * Dont forget to document your methods.
     * <dl>
     * <dt><b>Example:</b>
     * <pre>
     *       
           *   MyFunction does this and that
           *   @param Arg1
           *      The first argument of MyFunction.
           *   @return
           *      Error code of function.
           * 
     * virtual int MyFunction (int Arg1) = 0;
     * </pre>
     * </dl>
     */

  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};

//------------------------------------------------------------------

#endif
