// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CAAPuiPRDWorkshopConfigCmd.h
// The command: CAAPuiPRDWorkshopConfigCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Sep 2003  Creation: Code generated by the CAA wizard  avm
//===================================================================
#ifndef CAAPuiPRDWorkshopConfigCmd_H
#define CAAPuiPRDWorkshopConfigCmd_H

#include "CATCommand.h"

//----------------------------------------------------------------------

/**
 * Command for the CAAPuiPRDWorkshopConfig use case
 */
class CAAPuiPRDWorkshopConfigCmd: public CATCommand
{
public:

	CAAPuiPRDWorkshopConfigCmd();
	virtual ~CAAPuiPRDWorkshopConfigCmd();

	/**
	 * Activates a command.
	 * @param iFromClient 
	 *   The command that requests to activate the current one.
	 * @param iEvtDat
	 *   The notification sent.
	 */
	virtual CATStatusChangeRC Activate(CATCommand * iFromClient,
					   CATNotification * iEvtDat);

};

//----------------------------------------------------------------------

#endif
