// COPYRIGHT Dassault Systemes 2003
//===================================================================
//
// CAAPuiPRDWorkshopConfig.h
// Provide implementation to interface
//    CATIWorkbench
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Sep 2003  Creation: Code generated by the CAA wizard  avm
//===================================================================
#ifndef CAAPuiPRDWorkshopConfig_H
#define CAAPuiPRDWorkshopConfig_H

// System Framework
#include "CATBaseUnknown.h"  // Needed to derive from CATBaseUnknown
#include "CATListPV.h"       // Needed by GetCustomInterfaces
  
// ApplicationFrame Framework
class CATCmdWorkbench;       // Needed by CreateWorkbench

//-----------------------------------------------------------------------

/**
 * Class Object modeler implementation class.
 * <br>
 * It implements the interfaces :
 *  <ol>
 *  <li>CATIPRDWorkshopConfiguration @see ApplicationFrame.CATIWorkbench
 *  </ol>
 * Using this prefered syntax will enable mkdoc to document your class.
 */
class CAAPuiPRDWorkshopConfig: public CATBaseUnknown
{
	CATDeclareClass;

public:

	// Standard constructors and destructors for an implementation class
	// -----------------------------------------------------------------
	CAAPuiPRDWorkshopConfig ();
	virtual ~CAAPuiPRDWorkshopConfig ();

	/**
	 * @see ApplicationFrame.CATIWorkbench#CreateCommands
	 */
	void CreateCommands () ;

	/**
	 * @see ApplicationFrame.CATIWorkbench#CreateWorkbench
	 */
	CATCmdWorkbench * CreateWorkbench () ;

	/**
	 * @see ApplicationFrame.CATIWorkbench#GetAddinInterface
	 */
	CATClassId GetAddinInterface () ;

	/**
	 * @see ApplicationFrame.CATIWorkbench#GetCustomInterfaces
	 */
	void GetCustomInterfaces (CATListPV *iDefaultIIDList,
				  CATListPV *iCustomIIDList);


private:
	// The copy constructor and the equal operator must not be implemented
	// -------------------------------------------------------------------
	CAAPuiPRDWorkshopConfig (CAAPuiPRDWorkshopConfig &);
	CAAPuiPRDWorkshopConfig& operator=(CAAPuiPRDWorkshopConfig&);

};

//-----------------------------------------------------------------------

#endif
