# COPYRIGHT DASSAULT SYSTEMES 2003
#======================================================================
# Imakefile for module CAADrwAddin.m
#======================================================================
#
#  Sep 2003  Creation: Code generated by the CAA wizard  pjq
#======================================================================
#
# NONE 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)\
            JS0CORBA \
            CATApplicationFrame \
            DraftingItfCPP
            

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
